'use client';
import { useState } from 'react';
import Link from 'next/link';
import { api } from '../../../lib/api';
import { useData } from '../../../components/use-data';

type Item = { id: string; name?: string; title?: string; bio?: string; venue?: string; city?: string; status?: string; price_min?: string | null };
export default function EditPage() {
  const me = useData<{ user: { role: string } }>('/me');
  const [kind, setKind] = useState<'artists' | 'concerts'>('artists');
  const [slug, setSlug] = useState(''); const [item, setItem] = useState<Item | null>(null);
  const [name, setName] = useState(''); const [bio, setBio] = useState(''); const [venue, setVenue] = useState(''); const [city, setCity] = useState(''); const [status, setStatus] = useState('scheduled'); const [priceMin, setPriceMin] = useState('');
  const [platform, setPlatform] = useState('x'); const [accountUrl, setAccountUrl] = useState(''); const [externalId, setExternalId] = useState(''); const [message, setMessage] = useState('');
  async function load(event: React.FormEvent) { event.preventDefault(); try { const data = await api<Item>('/' + kind + '/' + encodeURIComponent(slug)); setItem(data); setName(data.name || data.title || ''); setBio(data.bio || ''); setVenue(data.venue || ''); setCity(data.city || ''); setStatus(data.status || 'scheduled'); setPriceMin(data.price_min || ''); setMessage(''); } catch (error) { setMessage((error as Error).message); } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!item) return; try { const body = kind === 'artists' ? { name, bio } : { title: name, venue, city, status, priceMin: priceMin ? Number(priceMin) : null }; await api('/admin/' + kind + '/' + item.id, { method: 'PATCH', body: JSON.stringify(body) }); setMessage('บันทึกการแก้ไขแล้ว'); } catch (error) { setMessage((error as Error).message); } }
  async function saveAccount(event: React.FormEvent) { event.preventDefault(); if (!item) return; try { await api('/admin/artists/' + item.id + '/accounts', { method: 'PUT', body: JSON.stringify({ platform, url: accountUrl, externalId: externalId || null }) }); setMessage('เพิ่มบัญชีทางการแล้ว'); setAccountUrl(''); } catch (error) { setMessage((error as Error).message); } }
  if (me.loading) return <p className="loading">กำลังตรวจสิทธิ์...</p>;
  if (me.data?.user.role !== 'admin') return <div className="container page"><p className="notice error">หน้านี้สำหรับผู้ดูแลเท่านั้น</p></div>;
  return <div className="container page"><div className="page-heading"><span className="eyebrow">ADMIN</span><h1>แก้ไขข้อมูล</h1><p><Link href="/admin" className="text-link">← กลับหน้าผู้ดูแล</Link></p></div><div className="assistant-grid"><section className="panel"><h2>ค้นหารายการ</h2><form className="budget-form" onSubmit={load}><label>ประเภท<select value={kind} onChange={(e) => { setKind(e.target.value as 'artists' | 'concerts'); setItem(null); }}><option value="artists">ศิลปิน</option><option value="concerts">คอนเสิร์ต</option></select></label><label>Slug<input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="จาก URL ของรายการ" required/></label><button className="button primary">โหลดข้อมูล</button></form></section>{item && <section className="panel"><h2>{item.name || item.title}</h2><form className="budget-form" onSubmit={save}><label>ชื่อ<input value={name} onChange={(e) => setName(e.target.value)} required/></label>{kind === 'artists' ? <label>ประวัติ<textarea value={bio} onChange={(e) => setBio(e.target.value)} rows={4}/></label> : <><label>สถานที่<input value={venue} onChange={(e) => setVenue(e.target.value)}/></label><label>เมือง<input value={city} onChange={(e) => setCity(e.target.value)}/></label><label>สถานะ<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="scheduled">ตามกำหนด</option><option value="postponed">เลื่อน</option><option value="cancelled">ยกเลิก</option><option value="completed">จบแล้ว</option></select></label><label>ราคาต่ำสุด<input type="number" min="0" value={priceMin} onChange={(e) => setPriceMin(e.target.value)}/></label></>}<button className="button primary">บันทึกแก้ไข</button></form>{kind === 'artists' && <><h3 className="spaced">บัญชีทางการที่ตรวจแล้ว</h3><form className="budget-form" onSubmit={saveAccount}><label>แพลตฟอร์ม<select value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="x">X</option><option value="facebook">Facebook</option><option value="instagram">Instagram</option><option value="website">เว็บไซต์</option></select></label><label>HTTPS URL<input type="url" value={accountUrl} onChange={(e) => setAccountUrl(e.target.value)} required/></label><label>Page/Business ID (ถ้ามีสิทธิ์ API)<input value={externalId} onChange={(e) => setExternalId(e.target.value)}/></label><button className="button secondary">เพิ่มบัญชี</button></form></>}</section>}</div>{message && <p className="notice">{message}</p>}</div>;
}
