// Primary-source reports and dated observations. No overall artist ranking.
export type ExpansionPopularityEvidence = {
  slug: string; status: 'verified-primary-report' | 'verified-snapshot' | 'indexed-primary-live-check-pending';
  metric: string; value: number | null; sourceUrl: string; sourceLabel: string; work: string;
  sourceDate: string | null; measuredAt: string | null; checkedAt: string; note: string; accountUrl?: string;
};

export const artistExpansionPopularityEvidence: { checkedAt: string; timezone: string; counts: { verified: number; pending: number; liveSnapshotsToday: number }; rows: ExpansionPopularityEvidence[] } = {
  "checkedAt": "2026-10-09T16:10:44.572Z",
  "timezone": "Asia/Bangkok",
  "counts": {
    "verified": 44,
    "pending": 6,
    "liveSnapshotsToday": 26
  },
  "rows": [
    {
      "slug": "blue-pongtiwat",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 56602,
      "sourceUrl": "https://open.spotify.com/artist/2qOLzlqMqg4sUAcwdO4tYJ",
      "sourceLabel": "Spotify — BLUE PONGTIWAT",
      "work": "BLUE PONGTIWAT",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:35.613Z",
      "checkedAt": "2026-10-09T11:48:35.613Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "chart-suchart",
      "status": "verified-primary-report",
      "metric": "reported_music_video_views_threshold",
      "value": 106000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "BACKPACK",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายรายงาน MV มากกว่า 106 ล้านวิว ไม่ระบุวันวัดและ URL upload จึงไม่ใช้เป็น live YouTube counter; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "copter",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.youtube.com/embed/niEybGRancQ",
      "sourceLabel": "LOVEiS — COPTER",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "de-flamingo",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 40918,
      "sourceUrl": "https://open.spotify.com/artist/4AiSuU5gTv0e66EqfwDRww",
      "sourceLabel": "Spotify — De Flamingo",
      "work": "De Flamingo",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:34.861Z",
      "checkedAt": "2026-10-09T16:07:34.861Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "fetch",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.youtube.com/embed/0wnVAdywnsE",
      "sourceLabel": "LOVEiS — FETCH",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "fourth",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 578000,
      "sourceUrl": "https://open.spotify.com/artist/4PtJISxBNvXOwLxuQgUiyQ",
      "sourceLabel": "Spotify — FOURTH",
      "work": "FOURTH",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:49:00.320Z",
      "checkedAt": "2026-10-09T11:49:00.320Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "gabe-watkins",
      "status": "verified-primary-report",
      "metric": "reported_streams_scope_unspecified_threshold",
      "value": 200000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "One Summer / Blue Skies",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายระบุเกิน 200,000 streams คู่กับสองเพลงนี้ ไม่ระบุแพลตฟอร์มหรือแยกยอดแต่ละเพลง ห้ามตีความเป็น Spotify หรือหารยอดให้เพลง; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "gawin",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 169117,
      "sourceUrl": "https://open.spotify.com/artist/6KLzn6hqkx6hk8o9X2fTpN",
      "sourceLabel": "Spotify — GAWIN",
      "work": "GAWIN",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:55.815Z",
      "checkedAt": "2026-10-09T11:48:55.815Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "gemini",
      "status": "verified-primary-report",
      "metric": "reported_x_event_trend_rank",
      "value": 1,
      "sourceUrl": "https://www.gmm-tv.com/news/4418/",
      "sourceLabel": "GMMTV",
      "work": "GEMINI ART-VENTURE CONCERT",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:39:07.282Z",
      "note": "GMMTV รายงานแฮชแท็กคอนเสิร์ตเดี่ยวขึ้นอันดับ 1 Worldwide ใน 4–6 ก.ย. 2026 ไม่ใช่อันดับศิลปินโดยรวม; ยังไม่ได้ตรวจ historical X API แยกต่างหาก; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "gun-napat",
      "status": "verified-primary-report",
      "metric": "artist_reported_tour_most_cities_sold_out",
      "value": null,
      "sourceUrl": "https://www.instagram.com/p/Dd0fllVHJ_U/",
      "sourceLabel": "บัญชีศิลปินทางการ",
      "work": "Gun Napat live in USA 2026",
      "sourceDate": "2026-09-28",
      "measuredAt": null,
      "checkedAt": "2026-10-09T10:24:54.656Z",
      "note": "ศิลปินรายงานเองว่าทัวร์ 6 เมืองขายบัตรหมดแทบทุกเมือง ไม่ใช่ครบทั้ง 6 เมืองและไม่มีจำนวนที่นั่ง; ใช้ข้อความโพสต์ที่ระบบเก็บแล้ว ไม่เรียก IG เพิ่ม; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้",
      "accountUrl": "https://www.instagram.com/gunnapat23/"
    },
    {
      "slug": "hens",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 1868,
      "sourceUrl": "https://open.spotify.com/artist/0lzGjtSmG50cgoi3knqZwA",
      "sourceLabel": "Spotify — HENS",
      "work": "HENS",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:50.979Z",
      "checkedAt": "2026-10-09T16:07:50.979Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "hers",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 151936,
      "sourceUrl": "https://open.spotify.com/artist/6QUnooiFt7qW7GiCtcdqWg",
      "sourceLabel": "Spotify — Hers",
      "work": "Hers",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:36.723Z",
      "checkedAt": "2026-10-09T16:07:36.723Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "hong-lykn",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.gmm-tv.com/artists/view/47/",
      "sourceLabel": "GMMTV — Hong (LYKN)",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "jeep",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 53405,
      "sourceUrl": "https://open.spotify.com/artist/3SHZIwDKgpVv86LfYJNGy2",
      "sourceLabel": "Spotify — JEEP",
      "work": "JEEP",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:10:37.367Z",
      "checkedAt": "2026-10-09T16:10:37.367Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "krist",
      "status": "verified-primary-report",
      "metric": "reported_joint_event_sold_out",
      "value": null,
      "sourceUrl": "https://www.gmm-tv.com/news/3784/",
      "sourceLabel": "GMMTV",
      "work": "The First Ex-Morning",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:39:08.342Z",
      "note": "ผู้จัดรายงานงานดูซีรีส์ร่วมของ Krist และ Singto ขายบัตรหมด ไม่ใช่คอนเสิร์ตเดี่ยว ไม่เปิดเผยจำนวนที่นั่ง และแยกความนิยมรายคนไม่ได้; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "ladiiprang",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 73900,
      "sourceUrl": "https://open.spotify.com/artist/5bAPqOCPEHPnrJWCbiA6SC",
      "sourceLabel": "Spotify — LADIIPRANG",
      "work": "LADIIPRANG",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:39.902Z",
      "checkedAt": "2026-10-09T11:48:39.902Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "landokmai",
      "status": "verified-primary-report",
      "metric": "reported_video_views_threshold",
      "value": 11000000,
      "sourceUrl": "https://www.whattheduckmusic.com/post/all-my-purple-feelings",
      "sourceLabel": "What The Duck",
      "work": "เพลงรักเพลงแรก",
      "sourceDate": "2024-02-01",
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:39:04.140Z",
      "note": "ค่ายรายงานมากกว่า 11 ล้านวิวในบทความวันที่ 1 ก.พ. 2024; Spotify 8 ล้านและ TikTok 100,000 คลิปเป็นคนละตัวชี้วัด ไม่รวมยอดเข้าด้วยกัน; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "lego-lykn",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.gmm-tv.com/artists/view/71/",
      "sourceLabel": "GMMTV — Lego (LYKN)",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "loserpop",
      "status": "verified-primary-report",
      "metric": "reported_multiple_music_video_views_threshold",
      "value": 1000000,
      "sourceUrl": "https://www.whattheduckmusic.com/post/ฉันและน้ำตา-drops",
      "sourceLabel": "What The Duck",
      "work": "เพลงใน Stupid Love Song ที่ค่ายระบุ",
      "sourceDate": "2022-01-19",
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:39:06.269Z",
      "note": "ค่ายรายงานหลายเพลงเกินล้านวิวในบทความ 19 ม.ค. 2022; ตัวเลขเป็น threshold ต่อเพลงที่รายงาน ไม่ใช่ยอดรวมอัลบั้มหรือจำนวนแฟน; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "marc-tatchapon",
      "status": "verified-primary-report",
      "metric": "reported_spotify_streams_scope_unspecified_threshold",
      "value": 2700000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "ผลงานที่กล่าวถึงในหน้าแนะนำ Marc Tatchapon",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายระบุเกิน 2.7 ล้าน Spotify streams หลังรายชื่อซิงเกิลและฝันสลาย แต่ขอบเขตยอดยังไม่ชัด ไม่ถือว่าเป็นยอดรายเพลงที่วัดจาก Spotify โดยตรง; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "mean-band",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 1025755,
      "sourceUrl": "https://open.spotify.com/artist/5fYMwzhko3iLCsqNhy07NG",
      "sourceLabel": "Spotify — MEAN Band",
      "work": "MEAN Band",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:37.078Z",
      "checkedAt": "2026-10-09T11:48:37.078Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "mints",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 3128,
      "sourceUrl": "https://open.spotify.com/artist/6mehI8OceoNGRHfevtc4l0",
      "sourceLabel": "Spotify — mints",
      "work": "mints",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:10:41.009Z",
      "checkedAt": "2026-10-09T16:10:41.009Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "mirrr",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 14081883,
      "sourceUrl": "https://www.youtube.com/watch?v=pol3UYEtQEo",
      "sourceLabel": "Whattheduck",
      "work": "Mirrr - ตลอดไปไม่มีจริง (NO!FOREVER?) Ft. Aheye 4EVE [Official MV]",
      "sourceDate": "2021-12-01",
      "measuredAt": "2026-10-04T07:41:26.254Z",
      "checkedAt": "2026-10-04T07:41:26.254Z",
      "note": "ใช้ snapshot ที่วัดจริงเมื่อ 4 ต.ค. 2026 ไม่ทำเวลาเก่าให้เป็นข้อมูลสดวันนี้; เป็นผลงานร่วม Mirrr และ Aheye 4EVE ยอดเป็นของวิดีโอร่วมทั้งชิ้น ไม่แยกยอดรายคน; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "mobye",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 20687,
      "sourceUrl": "https://open.spotify.com/artist/3Z5VM48ceWJTBmVqoZKAK5",
      "sourceLabel": "Spotify — MOBYE",
      "work": "MOBYE",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:44.203Z",
      "checkedAt": "2026-10-09T11:48:44.203Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "morvasu",
      "status": "verified-primary-report",
      "metric": "reported_youtube_video_views_threshold",
      "value": 55000000,
      "sourceUrl": "https://www.whattheduckmusic.com/post/party-girl",
      "sourceLabel": "What The Duck",
      "work": "Melbourne",
      "sourceDate": "2026-02-26",
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:59.797Z",
      "note": "ค่ายรายงานมากกว่า 55 ล้านวิวบน YouTube ตามบทความ Party Girl ปี 2026 ไม่ใช่ยอดวัดใหม่; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "nanon",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 16046838,
      "sourceUrl": "https://www.youtube.com/watch?v=iMdTPsd-nQA",
      "sourceLabel": "RISER MUSIC",
      "work": "KNOCK KNOCK - NANON x Jorin 4EVE Prod. by URBOYTJ [ OFFICIAL MV ]",
      "sourceDate": "2023-06-21",
      "measuredAt": "2026-10-04T07:41:25.569Z",
      "checkedAt": "2026-10-04T07:41:25.569Z",
      "note": "ใช้ snapshot ที่วัดจริงเมื่อ 4 ต.ค. 2026 ไม่ทำเวลาเก่าให้เป็นข้อมูลสดวันนี้; เป็นผลงานร่วม NANON และ Jorin 4EVE ยอดเป็นของวิดีโอร่วมทั้งชิ้น ไม่แยกยอดรายคน; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "newery",
      "status": "verified-primary-report",
      "metric": "reported_video_views_threshold",
      "value": 100000000,
      "sourceUrl": "https://www.whattheduckmusic.com/post/ดวงเดียว-missing",
      "sourceLabel": "What The Duck",
      "work": "กลิ่นดอกไม้",
      "sourceDate": "2025-02-21",
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:39:01.544Z",
      "note": "ค่ายรายงานมากกว่า 100 ล้านวิวในบทความวันที่ 21 ก.พ. 2025; ไม่ระบุ upload หรือวันวัดจริง; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "nut-lykn",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.gmm-tv.com/artists/view/100/",
      "sourceLabel": "GMMTV — Nut (LYKN)",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "oabnithi",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 194799,
      "sourceUrl": "https://open.spotify.com/artist/0POiRdWHPEPL1bhVAyLpAv",
      "sourceLabel": "Spotify — OABNITHI",
      "work": "OABNITHI",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:42.827Z",
      "checkedAt": "2026-10-09T11:48:42.827Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "pae-arak",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 23234,
      "sourceUrl": "https://open.spotify.com/artist/3Mg1Mn6ZnRsPxZZzmxXPjT",
      "sourceLabel": "Spotify — Pae Arak",
      "work": "Pae Arak",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:40.243Z",
      "checkedAt": "2026-10-09T16:07:40.243Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "pango",
      "status": "verified-primary-report",
      "metric": "reported_cover_video_views",
      "value": 1000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "วิดีโอ cover ช่วงเริ่มต้นอาชีพ",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายกล่าวถึง 1 ล้านวิวในช่วงเริ่มอาชีพ แต่ไม่ระบุชื่อวิดีโอ วันวัด หรือว่าเป็นยอดรวมกี่ชิ้น ไม่ผูกตัวเลขนี้กับซิงเกิลปัจจุบัน; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "peaksayaa",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 826,
      "sourceUrl": "https://open.spotify.com/artist/4fpwdYCe1CPV9MbILA1WeF",
      "sourceLabel": "Spotify — PEAKSayaa!",
      "work": "PEAKSayaa!",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:54.677Z",
      "checkedAt": "2026-10-09T16:07:54.677Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "plastic-plastic",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 47584,
      "sourceUrl": "https://open.spotify.com/artist/0YjEWrRKD9nBJfeF5eLdBd",
      "sourceLabel": "Spotify — Plastic Plastic",
      "work": "Plastic Plastic",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:38.486Z",
      "checkedAt": "2026-10-09T16:07:38.486Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "ponchet",
      "status": "verified-primary-report",
      "metric": "reported_youtube_video_views_threshold",
      "value": 50000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "พี่ชอบหนูที่สุดเลย",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายรายงานมากกว่า 50 ล้านวิวบน YouTube ไม่ใช่ยอด cover ของศิลปินคนอื่นและไม่ใช่ counter สด; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "puimekster",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 2226,
      "sourceUrl": "https://open.spotify.com/artist/1J4CZAHBaCdOr4hGth4K9i",
      "sourceLabel": "Spotify — PUIMEKSTER",
      "work": "PUIMEKSTER",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:41.267Z",
      "checkedAt": "2026-10-09T11:48:41.267Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "qler",
      "status": "verified-primary-report",
      "metric": "reported_youtube_video_views_threshold",
      "value": 39000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "จีบ",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายรายงาน YouTube มากกว่า 39 ล้านวิว ไม่ระบุวันวัด; หลักฐานนี้อยู่ในส่วน QLER โดยตรง; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "rooftop",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 201930,
      "sourceUrl": "https://open.spotify.com/artist/3wzGjN26jzqLY2Gc836sjC",
      "sourceLabel": "Spotify — ROOFTOP",
      "work": "ROOFTOP",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:45.611Z",
      "checkedAt": "2026-10-09T11:48:45.611Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "sarah-salola",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 201885,
      "sourceUrl": "https://open.spotify.com/artist/70ircOPIxsddNpd8Vgq23E",
      "sourceLabel": "Spotify — sarah salola",
      "work": "sarah salola",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:34.032Z",
      "checkedAt": "2026-10-09T11:48:34.032Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "slapkiss",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 291523,
      "sourceUrl": "https://open.spotify.com/artist/6GBIcdZ5aBhhsd7Y6c3O3g",
      "sourceLabel": "Spotify — Slapkiss",
      "work": "Slapkiss",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:38.575Z",
      "checkedAt": "2026-10-09T11:48:38.575Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "tace",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 19508,
      "sourceUrl": "https://open.spotify.com/artist/0WLaH3FRfeusfU2M7p95s5",
      "sourceLabel": "Spotify — TACE",
      "work": "TACE",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:10:44.528Z",
      "checkedAt": "2026-10-09T16:10:44.528Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "teyataye",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 141,
      "sourceUrl": "https://open.spotify.com/artist/7xjxDKGA00Zt9f4zEHynEv",
      "sourceLabel": "Spotify — TeyaTaye",
      "work": "TeyaTaye",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:59.955Z",
      "checkedAt": "2026-10-09T16:07:59.955Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "titi-nichaphat",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 159,
      "sourceUrl": "https://open.spotify.com/artist/5Xj4vMbStZeK3ONLGuug9N",
      "sourceLabel": "Spotify — TITI Nichaphat",
      "work": "TITI Nichaphat",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:47.064Z",
      "checkedAt": "2026-10-09T11:48:47.064Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "tonhon",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 301,
      "sourceUrl": "https://open.spotify.com/artist/4oWLiDNUCS097Cef0sfLN1",
      "sourceLabel": "Spotify — TONHON",
      "work": "TONHON",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:43.864Z",
      "checkedAt": "2026-10-09T16:07:43.864Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "tui-lykn",
      "status": "indexed-primary-live-check-pending",
      "metric": "individual_reach_pending",
      "value": null,
      "sourceUrl": "https://www.gmm-tv.com/artists/view/152/",
      "sourceLabel": "GMMTV — Tui (LYKN)",
      "work": "บัญชี/ผลงานต้นทางที่ต้องตรวจตัวเลขเพิ่ม",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:41:25.679Z",
      "note": "ยืนยันช่องทางหรือผลงานจากต้นสังกัดได้ แต่ยังไม่มีตัวเลขความนิยมที่ตรวจยืนยันเฉพาะราย; YouTube watch ตัวอย่างตอบ 429 จึงหยุดชุดอ่าน ไม่ถือว่าทุกบัญชีตอบ 429 ไม่ใช้ยอดรวมค่ายหรือวงแทนรายบุคคล"
    },
    {
      "slug": "uncle-ben",
      "status": "verified-primary-report",
      "metric": "reported_youtube_video_views",
      "value": 52000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "อย่าเป็นฉันเลย",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายรายงาน YouTube 52 ล้านวิว ไม่ระบุวันวัดหรือ upload จึงเก็บเป็นรายงานค่าย; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "valentina-ploy",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 197953,
      "sourceUrl": "https://open.spotify.com/artist/4RnzpVhMevUeU16FlV4e3e",
      "sourceLabel": "Spotify — Valentina Ploy",
      "work": "Valentina Ploy",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:42.105Z",
      "checkedAt": "2026-10-09T16:07:42.105Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "wanwanwan",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 63125,
      "sourceUrl": "https://open.spotify.com/artist/0QScRPnsnAmEpN7w3p1Joo",
      "sourceLabel": "Spotify — WANWANWAN",
      "work": "WANWANWAN",
      "sourceDate": null,
      "measuredAt": "2026-10-09T16:07:47.520Z",
      "checkedAt": "2026-10-09T16:07:47.520Z",
      "note": "ผู้ฟังรายเดือนจากหน้า Spotify สาธารณะที่ตรวจชื่อและผลงานตรงกับศิลปิน; ไม่ใช่ยอดผู้ติดตาม สตรีม หรืออันดับรวม เป็น snapshot ไม่อัปเดตอัตโนมัติ และไม่ใช้ยอดวงแทนรายบุคคล"
    },
    {
      "slug": "whal-dolph",
      "status": "verified-primary-report",
      "metric": "reported_ticket_sellout_minutes",
      "value": 10,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "Fish Market ณ Voice Space",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายรายงานว่าบัตรหมดภายใน 10 นาที ไม่ระบุวันวัด จำนวนที่นั่ง หรือยอดขาย; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    },
    {
      "slug": "william-lykn",
      "status": "verified-snapshot",
      "metric": "spotify_monthly_listeners",
      "value": 471938,
      "sourceUrl": "https://open.spotify.com/artist/51sFFBq8BCtciQk7VqsDTJ",
      "sourceLabel": "Spotify — William Jakrapatr",
      "work": "William Jakrapatr",
      "sourceDate": null,
      "measuredAt": "2026-10-09T11:48:57.277Z",
      "checkedAt": "2026-10-09T11:48:57.277Z",
      "note": "จำนวนผู้ฟังรายเดือนของโปรไฟล์ศิลปิน ณ เวลาตรวจจากหน้า Spotify สาธารณะ; ไม่ใช่จำนวนผู้ติดตาม ยอดสตรีม อันดับรวม หรือค่าที่อัปเดตอัตโนมัติ ไม่ใช้ยอดวงแทนสมาชิก"
    },
    {
      "slug": "yourmood",
      "status": "verified-primary-report",
      "metric": "reported_spotify_streams_scope_unspecified_threshold",
      "value": 61000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceLabel": "What The Duck",
      "work": "ผลงานที่กล่าวถึงในหน้าแนะนำ YourMOOD",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-09T11:38:58.491Z",
      "note": "ค่ายระบุเกิน 61,000 Spotify streams หลังรายชื่อหลายเพลงและ Your guy ไม่ชัดว่าเป็นยอดเพลงเดียวหรือหลายเพลง จึงไม่ผูกยอดกับซิงเกิลเดียว; เป็นข้อมูลผลงาน/กิจกรรมเฉพาะรายการและช่วงเวลาของต้นทาง ไม่ใช่อันดับความนิยมรวม จำนวนแฟน หรือค่าที่วัดสดวันนี้"
    }
  ]
};
