// Dated observations; different metrics must not be combined into a current artist ranking.
export const artistPopularityEvidence = {
  "checkedAt": "2026-10-03T17:09:20.748Z",
  "timezone": "Asia/Bangkok",
  "dateRange": "2026-10-03/2026-10-04",
  "counts": {
    "verified-primary-report": 10,
    "verified-snapshot": 18,
    "indexed-primary-live-check-pending": 2,
    "collective-only-individual-pending": 7
  },
  "rows": [
    {
      "slug": "bodyslam",
      "status": "verified-primary-report",
      "metric": "chart_rank",
      "value": 1,
      "sourceUrl": "https://www.gmmgrammy.com/newsroom/news-single.php?id=10418",
      "sourceDate": "2026-07-08",
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "GMM Music รายงาน Top Artist บน YouTube Charts ไทยอันดับ 1 เมื่อเปิดชาร์ต; ยืนยันคำรายงานของค่าย ไม่ใช่อันดับสัปดาห์นี้"
    },
    {
      "slug": "tilly-birds",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 37445956,
      "measuredAt": "2026-10-03T17:02:42.068Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=V1_LViinG0U",
      "sourceLabel": "GeneLab",
      "work": "คิด(แต่ไม่)ถึง [Same Page?] - Tilly Birds |Lyric Video|",
      "note": ""
    },
    {
      "slug": "three-man-down",
      "status": "verified-primary-report",
      "metric": "spotify_album_streams_lower_bound",
      "value": 360000000,
      "sourceUrl": "https://www.kruengkao.com/en/artist/three-man-down",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "ผู้จัดการรายงานอัลบั้ม This City Won’t Be Lonely Anymore มากกว่า 360 ล้านสตรีม; หน้าไม่ระบุวันวัด"
    },
    {
      "slug": "cocktail",
      "status": "verified-primary-report",
      "metric": "consecutive_weeks_at_chart_rank_one",
      "value": 8,
      "sourceUrl": "https://investor.gmmgrammy.com/storage/downloads/shareholders-meeting/agm2022/20220325-grammy-agm-2022-enc02-en.pdf",
      "sourceDate": "2021-04-30",
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "รายงานประชุม AGM 2021 หน้า 13 กล่าวถึงผลงานปี 2020: ดึงดัน อันดับ 1 JOOX Thailand Top 100 ต่อเนื่อง 8 สัปดาห์; ไม่ใช่ความนิยมล่าสุด"
    },
    {
      "slug": "slot-machine",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 187808450,
      "measuredAt": "2026-10-03T17:02:24.387Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=UZxDLz-li_c",
      "sourceLabel": "TERO MUSIC",
      "work": "Slot Machine: เคลิ้ม - KLOEM [Official Music Video]",
      "note": ""
    },
    {
      "slug": "getsunova",
      "status": "verified-primary-report",
      "metric": "youtube_song_views_lower_bound",
      "value": 200000000,
      "sourceUrl": "https://www.gmmgrammy.com/newsroom/news-single.php?id=1515",
      "sourceDate": "2016-01-26",
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "ค่ายรายงาน ไกลแค่ไหนคือใกล้ ทะลุ 200 ล้านวิว; เป็นสถิติอดีต"
    },
    {
      "slug": "polycat",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 17466877,
      "measuredAt": "2026-10-03T17:02:25.209Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=lBhIgPGCgbI",
      "sourceLabel": "SMALLROOM",
      "work": "POLYCAT - ข้อความรูปยิ้ม :) [Music Video]",
      "note": ""
    },
    {
      "slug": "4eve",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 3738268,
      "measuredAt": "2026-10-03T17:02:41.382Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "sourceLabel": "4EVE",
      "work": "4EVE - Too Perfect For You (สวย เริ่ด เชิด) | OFFICIAL MV",
      "note": ""
    },
    {
      "slug": "bus",
      "status": "verified-primary-report",
      "metric": "youtube_music_videos_threshold",
      "value": 10000000,
      "sourceUrl": "https://www.universal-music.co.jp/bus-becauseofyouishine/biography/",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "Universal Japan รายงานหลาย MV เกิน 10 ล้านวิว และ TRANSFORMER 1 ล้านวิวใน 24 ชั่วโมง; ไม่ระบุวันวัด"
    },
    {
      "slug": "proxie",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 32886,
      "measuredAt": "2026-10-03T17:02:41.383Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=FZvL0S-jOms",
      "sourceLabel": "PROXIE",
      "work": "PROXIE - ตบปาก (On That Day) | MV Teaser",
      "note": "เป็นยอดดู MV teaser เท่านั้น; ไม่เพียงพอใช้แทนยอดผลงานหลักหรือสรุปว่าความนิยมต่ำ; MV คนไม่คุยที่พบอ่านค่าปัจจุบันไม่สำเร็จ HTTP 429"
    },
    {
      "slug": "pixxie",
      "status": "verified-primary-report",
      "metric": "spotify_song_streams_lower_bound",
      "value": 36000000,
      "sourceUrl": "https://www.universal-music.co.jp/pixxie/news/2026-07-17-3/",
      "sourceDate": "2026-07-17",
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "Universal Japan รายงาน Whatever เกิน 36 ล้านสตรีม Spotify"
    },
    {
      "slug": "atlas",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 8269041,
      "measuredAt": "2026-10-03T17:02:26.727Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=K_78MhK616M",
      "sourceLabel": "ATLAS",
      "work": "ATLAS - แกล้งลืม (Boyfriend) (Prod. by NINO) | Official MV",
      "note": ""
    },
    {
      "slug": "jeff-satur",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 265755568,
      "measuredAt": "2026-10-03T17:02:27.325Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=6f5sozKp0R0",
      "sourceLabel": "Jeff Satur",
      "work": "Jeff Satur - ลืมไปแล้วว่าลืมยังไง (Fade)【Official Music Video】",
      "note": ""
    },
    {
      "slug": "nont-tanont",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 17723915,
      "measuredAt": "2026-10-03T17:02:28.903Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=238wVBszibE",
      "sourceLabel": "LOVEiS",
      "work": "NONT TANONT - คืนที่หมาเต็มวัด (Temple Dogs) ft. Singto Numchok [Official MV]",
      "note": "ผลงานร่วม Singto Numchok; ไม่แยกส่วนยอดดูให้แต่ละศิลปิน"
    },
    {
      "slug": "ink-waruntorn",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 69600741,
      "measuredAt": "2026-10-03T17:02:30.384Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=qyKVXta1vVY",
      "sourceLabel": "BOXX MUSIC",
      "work": "สักวันฉันจะหายดี - INK WARUNTORN [Official MV]",
      "note": ""
    },
    {
      "slug": "bowkylion",
      "status": "verified-primary-report",
      "metric": "youtube_songs_views_lower_bound",
      "value": 10000000,
      "sourceUrl": "https://www.whattheduckmusic.com/a",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "ค่ายกล่าวถึง recall / bad bowky / mint และยอดเกิน 10 ล้านวิว; ไม่แจกแจงค่ารายเพลง/วันวัด จึงไม่ใช้เป็นตัวเลขรวมที่แม่นยำ"
    },
    {
      "slug": "the-toys",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 210548,
      "measuredAt": "2026-10-03T17:02:34.961Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=uZr1Ny86XHI",
      "sourceLabel": "Whattheduck",
      "work": "THE TOYS - หน้าหนาวที่แล้ว [OFFICIAL AUDIO]",
      "note": "เป็น official audio upload นี้เท่านั้น ไม่ใช่ยอดของทุกเวอร์ชันของเพลง; ไม่เพียงพอใช้ตัดสินความนิยมโดยรวม"
    },
    {
      "slug": "milli",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 13721888,
      "measuredAt": "2026-10-03T17:02:37.724Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=kETLbg89qA0",
      "sourceLabel": "YUPP!",
      "work": "MILLI feat. ฮาย อาภาพร - HEY HEY 🙌🏻🙌🏻 (Prod. by SpatChies) | YUPP!",
      "note": "ผลงานร่วม ฮาย อาภาพร; ไม่แยกส่วนยอดดู"
    },
    {
      "slug": "phum-viphurit",
      "status": "verified-primary-report",
      "metric": "combined_spotify_youtube_song_streams_lower_bound",
      "value": 180000000,
      "sourceUrl": "https://shop.phumviphurit.com/pages/about-us",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "เว็บไซต์ศิลปินรายงาน Lover Boy เกิน 180 ล้าน Spotify + YouTube รวมกัน; วันวัดไม่ระบุ ห้ามเปรียบกับ YouTube อย่างเดียว"
    },
    {
      "slug": "violette-wautier",
      "status": "verified-primary-report",
      "metric": "reported_song_plays",
      "value": 60000000,
      "sourceUrl": "https://www.universal-music.co.jp/violette-wautier/biography/",
      "sourceDate": null,
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "Universal Japan รายงาน Smoke 60 ล้านการเล่น; ไม่ระบุแพลตฟอร์มหรือวันวัดที่ชัดเจน"
    },
    {
      "slug": "pp-krit",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 39211147,
      "measuredAt": "2026-10-03T17:02:38.671Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=NvBHCtMb5u8",
      "sourceLabel": "PP Krit Entertainment",
      "work": "PP KRIT - FIRE BOY [Official MV]",
      "note": ""
    },
    {
      "slug": "billkin",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 1495714,
      "measuredAt": "2026-10-03T17:02:38.671Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=6C_WabSBdHU",
      "sourceLabel": "Billkin Entertainment",
      "work": "BILLKIN - CHECKLIST - Official MV",
      "note": ""
    },
    {
      "slug": "palmy",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 12298753,
      "measuredAt": "2026-10-03T17:02:42.067Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=QaPxz1I2nto",
      "sourceLabel": "Genierock",
      "work": "หลุมอากาศ - PALMY「Official MV」",
      "note": ""
    },
    {
      "slug": "stamp-apiwat",
      "status": "indexed-primary-live-check-pending",
      "metric": "youtube_video_views_indexed",
      "value": 50384333,
      "sourceUrl": "https://www.youtube.com/watch?v=OS8-m0sdF4c",
      "sourceLabel": "Stamp&Jeri",
      "work": "ถ้าเธอ — STAMP & Violette Wautier",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "ตัวเลขจากข้อมูลหน้า YouTube ในผลค้นหา; การอ่านหน้าจริงรอบนี้ HTTP 429 จึงไม่รับรองเป็นค่าปัจจุบัน; ผลงานร่วม ไม่แยกยอดดู"
    },
    {
      "slug": "tattoo-colour",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 14607926,
      "measuredAt": "2026-10-03T17:02:38.672Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=ZP6EgIToxyA",
      "sourceLabel": "SMALLROOM",
      "work": "TATTOO COLOUR - ขอให้เราทั้งคู่โชคดี | Good Luck to The Both of Us [Music Video]",
      "note": ""
    },
    {
      "slug": "scrubb",
      "status": "indexed-primary-live-check-pending",
      "metric": "youtube_video_views_indexed",
      "value": 6702920,
      "sourceUrl": "https://www.youtube.com/watch?v=SDvYqwJ0Vy0",
      "sourceLabel": "SCRUBB MUSIC TUBE",
      "work": "คู่กัน (Official Music Video)",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "ตัวเลขจากข้อมูลหน้า YouTube ในผลค้นหา; การอ่านหน้าจริงรอบนี้ HTTP 429 จึงไม่รับรองเป็นค่าปัจจุบัน"
    },
    {
      "slug": "musketeers",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 7448852,
      "measuredAt": "2026-10-03T17:02:34.961Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=hEb9VpVMsXc",
      "sourceLabel": "Whattheduck",
      "work": "Musketeers - รวมเพลงฮิต (Longplay)",
      "note": "วิดีโอรวมเพลง Longplay; ห้ามนับเทียบเป็นยอดเพลงเดียว"
    },
    {
      "slug": "paper-planes",
      "status": "verified-primary-report",
      "metric": "reported_awards",
      "value": 12,
      "sourceUrl": "https://www.gmmgrammy.com/newsroom/news-single.php?id=9927",
      "sourceDate": "2023-06-28",
      "measuredAt": null,
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "note": "ค่ายแจกแจง 12 รางวัลจาก 8 เวทีในครึ่งแรกปี 2023; เป็นหลักฐาน recognition ในอดีต ไม่ใช่คะแนนความนิยมปัจจุบัน"
    },
    {
      "slug": "only-monday",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 4733618,
      "measuredAt": "2026-10-03T17:02:40.028Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=3W6LbVRiRsQ",
      "sourceLabel": "Only Monday Official",
      "work": "ฉันโกหกว่าไม่เป็นไรหรอกมั้ง - FOOL STEP x ONLY MONDAY (Mashup Ver.)",
      "note": "Mashup ร่วม FOOL STEP; ไม่แยกส่วนยอดดู"
    },
    {
      "slug": "dept",
      "status": "verified-snapshot",
      "metric": "youtube_video_views",
      "value": 2397323,
      "measuredAt": "2026-10-03T17:02:40.029Z",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "sourceUrl": "https://www.youtube.com/watch?v=Uy1le5Eo8Dw",
      "sourceLabel": "SMALLROOM",
      "work": "Dept - อยากเจอจะทนไม่ไหว | Dear Me [Music Video]",
      "note": ""
    },
    {
      "slug": "mind-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "jorin-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "taaom-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "hannah-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "fai-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "punch-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    },
    {
      "slug": "aheye-4eve",
      "status": "collective-only-individual-pending",
      "metric": "group_evidence_only",
      "value": null,
      "groupSlug": "4eve",
      "sourceUrl": "https://www.youtube.com/watch?v=4VA7IRiiS8c",
      "checkedAt": "2026-10-03T17:09:20.748Z",
      "measuredAt": null,
      "note": "คำอธิบาย MV ทางการระบุสมาชิกและบัญชีรายคน; ความนิยมอ้างอิงผลงานรวม 4EVE เท่านั้น ยังไม่มีตัวชี้วัดความนิยมรายบุคคลที่เทียบกันได้"
    }
  ]
};
