// Reviewed 2026-10-03 against artist/label pages and official video descriptions.
// A verified link does not guarantee API access to the account's media.
export const verifiedInstagramAccounts: Partial<Record<string, { handle: string; evidenceUrl: string }>> = {
  bodyslam: { handle: 'bodyslamband', evidenceUrl: 'https://linktr.ee/bodyslam' },
  'tilly-birds': { handle: 'tillybirds', evidenceUrl: 'https://www.tillybirds.com/about' },
  'three-man-down': { handle: 'threemandown', evidenceUrl: 'https://www.kruengkao.com/en/artist/three-man-down' },
  cocktail: { handle: 'cheerscocktail', evidenceUrl: 'https://universalmusic.fr/artistes/36484961805' },
  'slot-machine': { handle: 'slotmachinerock', evidenceUrl: 'https://slotmachine.band/bio.php' },
  getsunova: { handle: 'getsunova', evidenceUrl: 'https://www.gmmgrammy.com/newsroom/news-single.php?id=1471' },
  polycat: { handle: 'polycatband', evidenceUrl: 'https://smallroom.co.th/artist/1/polycat' },
  bus: { handle: 'bus.becauseofyouishine', evidenceUrl: 'https://www.busofficialmembership.com/th/' },
  proxie: { handle: 'proxie.officialth', evidenceUrl: 'https://www.youtube.com/watch?v=FZvL0S-jOms' },
  pixxie: { handle: 'pixxie_official', evidenceUrl: 'https://www.universal-music.co.jp/pixxie/' },
  'jeff-satur': { handle: 'jeffsatur', evidenceUrl: 'https://wmg.jp/jeffsatur' },
  'nont-tanont': { handle: 'tanont916', evidenceUrl: 'https://www.loveisentertainment.com/nont-tanont' },
  'ink-waruntorn': { handle: 'inkwaruntorn', evidenceUrl: 'https://www.youtube.com/watch?v=_NPF8DKkiIk' },
  bowkylion: { handle: 'bowkylion', evidenceUrl: 'https://www.whattheduckmusic.com/a' },
  'the-toys': { handle: 'thetoysthetoysthetoys', evidenceUrl: 'https://www.whattheduckmusic.com/a' },
  'violette-wautier': { handle: 'violettewautier', evidenceUrl: 'https://www.universal-music.co.jp/violette-wautier/biography/' },
  'pp-krit': { handle: 'pp.kritt', evidenceUrl: 'https://www.universal-music.co.jp/billkin-and-ppkrit/news/2023-07-31/' },
  palmy: { handle: 'palmy.ig', evidenceUrl: 'https://www.youtube.com/watch?v=QaPxz1I2nto' },
  'tattoo-colour': { handle: 'tattoocolourband', evidenceUrl: 'https://www.smallroom.co.th/artist/2/tattoo-colour' },
  scrubb: { handle: 'scrubbband', evidenceUrl: 'https://www.universal-music.co.jp/scrubb/' },
  musketeers: { handle: 'musketeersband', evidenceUrl: 'https://www.whattheduckmusic.com/a' },
  'paper-planes': { handle: 'paperplanesbandofficial', evidenceUrl: 'https://linktr.ee/paperplanesband' },
  'only-monday': { handle: 'onlymonday.band', evidenceUrl: 'https://linktr.ee/onlymonday' },
  dept: { handle: 'dept.dept', evidenceUrl: 'https://www.smallroom.co.th/artist/3/Dept' },
  'mind-4eve': { handle: '_.tiya_', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'jorin-4eve': { handle: 'jorinja', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'taaom-4eve': { handle: 'taaoem', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'hannah-4eve': { handle: 'hannah_kmz', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'fai-4eve': { handle: 'callmebanananana', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'punch-4eve': { handle: 'ppunnch', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
  'aheye-4eve': { handle: 'aheyekrn_', evidenceUrl: 'https://www.youtube.com/watch?v=4VA7IRiiS8c' },
};
