import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import test from 'node:test';
import pg from 'pg';
import { pool } from './db.js';
import { saveEvent, saveSourceEvents } from './ingest.js';
import type { ConcertEvent } from './concert-types.js';

test('Concert persistence retains rounds/history, canonical identity, manual and organizer precedence', { skip: !process.env.INGEST_TEST_DATABASE_URL }, async (t) => {
  const client = new pg.Client({ connectionString: process.env.INGEST_TEST_DATABASE_URL });
  await client.connect();
  try {
    await client.query('BEGIN');
    await client.query('CREATE SCHEMA concert_persistence_fixture');
    await client.query('SET LOCAL search_path TO concert_persistence_fixture,public');
    const dir = new URL('../sql/',import.meta.url);
    for (const file of (await readdir(dir)).filter(name => name.endsWith('.sql')).sort()) await client.query(await readFile(new URL(file,dir),'utf8'));
    t.mock.method(pool,'query',(sql: string,params: unknown[]) => client.query(sql,params));
    const base: ConcertEvent = { title: 'Fixture Live',url: 'https://www.theconcert.com/p/123',venue: 'Hall A',country: 'TH',startsAt: '2030-12-25T09:00:00Z',endsAt: '2030-12-25T16:00:00Z',priceMin: 350,priceMax: 350,completeSchedule: true,image: 'https://example.com/actual-poster.jpg' };
    await t.test('Venue source data survives missing detail but clears after a move; admin precedence is preserved',async()=>{
      const input={...base,url:'https://www.ticketmelon.com/fixture/location',title:'Location concert',venue:'Location Hall',venueLocation:{address:'99 Rama 1 Road, Bangkok',latitude:13.75,longitude:100.5}};
      await saveEvent('Ticketmelon',input);const row=(await client.query("SELECT * FROM concerts WHERE title='Location concert'")).rows[0];assert.equal(row.venue_location.address,input.venueLocation.address);
      await saveEvent('Ticketmelon',{...input,venueLocation:null});assert.equal((await client.query('SELECT venue_location FROM concerts WHERE id=$1',[row.id])).rows[0].venue_location.address,input.venueLocation.address);
      await saveEvent('Ticketmelon',{...input,venue:'Moved Hall',venueLocation:null});assert.equal((await client.query('SELECT venue_location FROM concerts WHERE id=$1',[row.id])).rows[0].venue_location,null);
      await client.query('UPDATE concerts SET manual_override=true WHERE id=$1',[row.id]);await saveEvent('Ticketmelon',input);assert.equal((await client.query('SELECT venue_location FROM concerts WHERE id=$1',[row.id])).rows[0].venue_location,null);
      await client.query('UPDATE concerts SET venue_location=$2 WHERE id=$1',[row.id,JSON.stringify({address:'Old address',latitude:13.75,longitude:100.5})]);
      await client.query("UPDATE concerts SET venue='Admin moved venue' WHERE id=$1",[row.id]);assert.equal((await client.query('SELECT venue_location FROM concerts WHERE id=$1',[row.id])).rows[0].venue_location,null,'Admin moves must clear the prior map point');
      await client.query('DELETE FROM concerts WHERE id=$1',[row.id]);
    });
    await saveSourceEvents('The Concert',[base,{ ...base,startsAt: '2030-12-26T09:00:00Z',endsAt: '2030-12-26T16:00:00Z',priceMin: 590,priceMax: 590 }]);
    let concert = (await client.query('SELECT * FROM concerts')).rows[0];
    assert.equal(concert.image_url,base.image); assert.equal(concert.image_source_url,base.url); assert.ok(concert.image_checked_at);
    await saveEvent('The Concert',{ ...base,image: null });
    const imageRetained = (await client.query('SELECT image_url,image_source_url,image_checked_at FROM concerts WHERE id=$1',[concert.id])).rows[0];
    assert.equal(imageRetained.image_url,base.image); assert.equal(imageRetained.image_source_url,base.url); assert.deepEqual(imageRetained.image_checked_at,concert.image_checked_at);
    assert.equal(concert.starts_at.toISOString(),base.startsAt!.replace('Z','.000Z'));
    assert.equal(Number(concert.price_min),350); assert.equal(Number(concert.price_max),590);
    assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances')).rows[0].n,2);
    await saveSourceEvents('The Concert',[{ ...base,startsAt: '2031-01-01T09:00:00Z',endsAt: null,status: 'postponed',priceMin: null,priceMax: null }]);
    assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances WHERE is_current')).rows[0].n,1);
    assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances')).rows[0].n,3);
    concert = (await client.query('SELECT * FROM concerts')).rows[0];
    assert.equal(concert.status,'postponed'); assert.equal(Number(concert.price_min),350); assert.match(concert.price_note,/ยังไม่ระบุราคา/);
    assert.equal(concert.ends_at,null,'An unannounced end time must not be replaced by the start time');
    await client.query('UPDATE concerts SET manual_override=true,title=$2 WHERE id=$1',[concert.id,'Admin correction']);
    await saveSourceEvents('The Concert',[{ ...base,startsAt: '2032-01-01T09:00:00Z',status: 'cancelled' }]);
    assert.equal((await client.query('SELECT title FROM concerts WHERE id=$1',[concert.id])).rows[0].title,'Admin correction');
    assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances')).rows[0].n,3);
    await saveEvent('Eventpop',{ ...base,title: 'Other Live',url: 'https://www.eventpop.me/e/999/old-slug' });
    await saveEvent('Eventpop',{ ...base,title: 'Other Live',url: 'https://www.eventpop.me/e/999' });
    assert.equal((await client.query('SELECT count(*)::int n FROM concerts')).rows[0].n,2);
    assert.equal(await saveEvent('Eventpop',{ ...base,url: 'https://www.eventpop.me/e/998',startsAt: null,status: 'cancelled' }),false);
    await saveEvent('Ticketmelon',{ ...base,url: 'https://www.ticketmelon.com/fixture/other-venue',venue: 'Hall B' });
    assert.equal((await client.query('SELECT count(*)::int n FROM concerts')).rows[0].n,3);
    await saveEvent('Live Nation Tero',{ ...base,title: 'Organizer Live',url: 'https://www.livenationtero.co.th/en/event/fixture',venue: 'Hall C' });
    await saveEvent('Ticketmelon',{ ...base,title: 'Organizer Live',url: 'https://www.ticketmelon.com/fixture/organizer',venue: 'Hall C',status: 'cancelled' });
    assert.equal((await client.query("SELECT status FROM concerts WHERE title='Organizer Live'")).rows[0].status,'scheduled');
    await t.test('Listing fallback cannot replace detail timestamps, prices, cancellation or manual corrections',async () => {
      const url = 'https://www.thaiticketmajor.com/concert/listing-fixture.html';
      await saveSourceEvents('ThaiTicketMajor',[{ ...base,url,title: 'Detail Protected',venue: 'Hall D',status: 'cancelled' }]);
      const before = (await client.query('SELECT c.*,s.fetched_at FROM concerts c JOIN concert_sources s ON s.concert_id=c.id WHERE s.source_url=$1',[url])).rows[0];
      await saveSourceEvents('ThaiTicketMajor',[{ ...base,url,title: 'Incomplete Card',venue: 'Wrong Hall',listingOnly: true,timeTba: true,startsAt: '2033-01-01T17:00:00Z',status: 'scheduled',priceMin: null,priceMax: null }]);
      const after = (await client.query('SELECT c.*,s.fetched_at,s.last_error FROM concerts c JOIN concert_sources s ON s.concert_id=c.id WHERE s.source_url=$1',[url])).rows[0];
      for (const key of ['title','venue','starts_at','ends_at','status','price_min','last_verified_at','fetched_at']) assert.deepEqual(after[key],before[key]);
      assert.match(after.last_error,/listing checked only/);
      const listing = { ...base,url: 'https://www.thaiticketmajor.com/concert/new-card.html',title: 'New Card',venue: 'Hall E',listingOnly: true,timeTba: true,endsAt: null,priceMin: null,priceMax: null };
      await saveSourceEvents('ThaiTicketMajor',[listing,{ ...listing,startsAt: '2030-12-26T09:00:00Z' }]);
      const fresh = (await client.query("SELECT * FROM concerts WHERE title='New Card'")).rows[0];
      assert.equal(fresh.last_verified_at,null);assert.equal(fresh.price_min,null);assert.equal(fresh.time_tba,true);assert.equal(fresh.starts_at.toISOString(),'2030-12-25T09:00:00.000Z');
      assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances WHERE concert_id=$1',[fresh.id])).rows[0].n,2);
      await client.query("UPDATE concerts SET manual_override=true,title='Manual listing' WHERE id=$1",[fresh.id]);
      await saveSourceEvents('ThaiTicketMajor',[{ ...listing,title: 'Wrong update' }]);
      assert.equal((await client.query('SELECT title FROM concerts WHERE id=$1',[fresh.id])).rows[0].title,'Manual listing');
      const organizerBefore = (await client.query("SELECT * FROM concerts WHERE title='Organizer Live'")).rows[0];
      await saveSourceEvents('ThaiTicketMajor',[{ ...base,title: 'Organizer Live',url: 'https://www.thaiticketmajor.com/concert/organizer-card.html',venue: 'Hall C',listingOnly: true,timeTba: true,priceMin: null,priceMax: null }]);
      const organizerAfter = (await client.query('SELECT * FROM concerts WHERE id=$1',[organizerBefore.id])).rows[0];
      assert.deepEqual(organizerAfter,organizerBefore,'A new listing source must not overwrite existing organizer details');
    });
    await t.test('Organizer input cannot persist an end before its own precise start',async () => {
      const event = { ...base,title: 'Invalid end fixture',url: 'https://www.livenationtero.co.th/invalid-end',venue: 'Hall Z',endsAt: '2030-12-24T17:00:00Z' };
      await saveSourceEvents('Live Nation Tero',[event]);
      const stored = (await client.query("SELECT * FROM concerts WHERE title='Invalid end fixture'")).rows[0];
      assert.equal(stored.ends_at,null);
      const rounds = (await client.query('SELECT ends_at FROM concert_performances WHERE concert_id=$1',[stored.id])).rows;
      assert.ok(rounds.every(row => row.ends_at===null));
    });
    await t.test('Additional listing dates supplement inaccessible details without replacing precise rounds or price verification',async () => {
      const url = 'https://www.thaiticketmajor.com/concert/extra-date-fixture.html';
      const full = { ...base,url,title: 'Additional date fixture',venue: 'Hall N',completeSchedule: false };
      await saveSourceEvents('ThaiTicketMajor',[full]);
      const before = (await client.query('SELECT c.*,s.fetched_at FROM concerts c JOIN concert_sources s ON s.concert_id=c.id WHERE s.source_url=$1',[url])).rows[0];
      const listing = { ...full,title: 'Listing title',timeTba: true,listingOnly: true,completeSchedule: false,priceMin: null,priceMax: null,endsAt: null };
      await saveSourceEvents('ThaiTicketMajor',[{ ...listing,startsAt: '2030-12-24T17:00:00Z' },{ ...listing,startsAt: '2030-12-25T17:00:00Z' }]);
      const after = (await client.query('SELECT c.*,s.fetched_at FROM concerts c JOIN concert_sources s ON s.concert_id=c.id WHERE s.source_url=$1',[url])).rows[0];
      assert.deepEqual(after,before,'A calendar supplement must not re-verify or overwrite full concert facts');
      const rounds = (await client.query('SELECT * FROM concert_performances WHERE concert_id=$1 ORDER BY starts_at',[before.id])).rows;
      assert.equal(rounds.length,2);assert.equal(rounds[0].time_tba,false);assert.equal(rounds[1].time_tba,true);
      assert.equal(rounds[1].ends_at,null);assert.match(rounds[1].performance_label,/ยังไม่ยืนยันเวลา/);
      await saveSourceEvents('ThaiTicketMajor',[{ ...listing,startsAt: '2030-12-23T17:00:00Z' }]);
      const earlier = (await client.query('SELECT * FROM concerts WHERE id=$1',[before.id])).rows[0];
      assert.equal(earlier.starts_at.toISOString(),'2030-12-23T17:00:00.000Z');assert.equal(earlier.time_tba,true);
      assert.equal(Number(earlier.price_min),350);assert.equal(earlier.last_verified_at,null);
      assert.equal((await client.query('SELECT time_tba FROM concert_performances WHERE concert_id=$1 AND starts_at=$2',[before.id,full.startsAt])).rows[0].time_tba,false);
      await client.query("UPDATE concerts SET venue='Live Streaming by TTM LIVE' WHERE id=$1",[before.id]);
      await saveSourceEvents('ThaiTicketMajor',[listing]);
      assert.equal((await client.query('SELECT venue FROM concerts WHERE id=$1',[before.id])).rows[0].venue,'Hall N');
      await client.query("UPDATE concerts SET status='cancelled' WHERE id=$1",[before.id]);
      await saveSourceEvents('ThaiTicketMajor',[{ ...listing,startsAt: '2030-12-26T17:00:00Z' }]);
      assert.equal((await client.query('SELECT count(*)::int n FROM concert_performances WHERE concert_id=$1',[before.id])).rows[0].n,3);
    });
    const user = (await client.query("INSERT INTO users(email,password_hash,display_name) VALUES('archive-fixture@example.com','fixture','Fixture') RETURNING id")).rows[0].id;
    for (const kind of ['invalid','manual','attended','mixed']) {
      const id = (await client.query("INSERT INTO concerts(slug,title,starts_at,manual_override) VALUES($1,$1,'2126-01-01',$2) RETURNING id",['archive-'+kind,kind === 'manual'])).rows[0].id;
      await client.query("INSERT INTO concert_sources(concert_id,source_name,source_url) VALUES($1,'Eventpop',$2)",[id,'https://www.eventpop.me/e/archive-'+kind]);
      if (kind === 'attended') await client.query('INSERT INTO attendance(user_id,concert_id) VALUES($1,$2)',[user,id]);
      if (kind === 'mixed') await client.query("INSERT INTO concert_sources(concert_id,source_name,source_url) VALUES($1,'Live Nation Tero',$2)",[id,'https://example.com/archive-mixed']);
    }
    await client.query(await readFile(new URL('013_eventpop_date_repair.sql',dir),'utf8'));
    assert.deepEqual((await client.query("SELECT slug FROM concerts WHERE slug LIKE 'archive-%' ORDER BY slug")).rows.map(row => row.slug),['archive-attended','archive-manual','archive-mixed']);
    const archive = (await client.query('SELECT snapshot FROM concert_date_archive')).rows;
    assert.equal(archive.length,1); assert.equal(archive[0].snapshot.concert.slug,'archive-invalid');
    assert.equal(archive[0].snapshot.sources.length,1);
  } finally {
    t.mock.restoreAll(); await client.query('ROLLBACK'); await client.end(); await pool.end();
  }
});
