import 'dotenv/config';

function boundedNumber(value: string | undefined, fallback: number, min: number, max: number) {
  const parsed = Number(value);
  return value && Number.isFinite(parsed) ? Math.max(min, Math.min(max, parsed)) : fallback;
}
const officialTicketmasterBase = 'https://app.ticketmaster.com/discovery/v2';
const configuredTicketmasterBase = process.env.TICKETMASTER_BASE_URL?.trim().replace(/\/+$/, '');

export const config = {
  databaseUrl: process.env.DATABASE_URL || 'postgres://artist:artist@localhost:5432/artist_tracker',
  port: Number(process.env.PORT || 4000),
  webOrigin: process.env.WEB_ORIGIN || 'http://localhost:3000',
  ollamaUrl: (process.env.OLLAMA_URL || 'http://localhost:11434').replace(/\/$/, ''),
  chatModel: process.env.OLLAMA_CHAT_MODEL || 'qwen3:8b',
  embedModel: process.env.OLLAMA_EMBED_MODEL || 'qwen3-embedding:0.6b',
  ollamaResource: process.env.OLLAMA_RESOURCE_ID || 'encore-local-gpu',
  ollamaQuietMs: boundedNumber(process.env.OLLAMA_BACKGROUND_QUIET_SECONDS, 15, 0, 300) * 1000,
  biographyOllamaUrl: (process.env.BIOGRAPHY_OLLAMA_URL || process.env.OLLAMA_URL || 'http://localhost:11434').replace(/\/$/, ''),
  biographyModel: process.env.BIOGRAPHY_MODEL || 'encore-biography:qwen3.8-27b',
  biographyEnabled: process.env.BIOGRAPHY_ENABLED !== 'false',
  biographyWindowStart: process.env.BIOGRAPHY_WINDOW_START || '23:00',
  biographyWindowEnd: process.env.BIOGRAPHY_WINDOW_END || '00:00',
  biographyMaxPerNight: Math.floor(boundedNumber(process.env.BIOGRAPHY_MAX_PER_NIGHT, 10, 1, 100)),
  biographyTimeoutMs: boundedNumber(process.env.BIOGRAPHY_TIMEOUT_SECONDS, 240, 30, 600) * 1000,
  xBearerToken: process.env.X_BEARER_TOKEN || '',
  xMonthlyLimitThb: Math.max(0, Math.min(350, Number(process.env.X_MONTHLY_LIMIT_THB || 350))),
  ticketmasterKey: process.env.TICKETMASTER_API_KEY || '',
  ticketmasterBaseUrl: configuredTicketmasterBase === officialTicketmasterBase ? configuredTicketmasterBase : officialTicketmasterBase,
  ticketmasterCountryCode: /^[A-Z]{2}$/.test(process.env.TICKETMASTER_COUNTRY_CODE || '') ? process.env.TICKETMASTER_COUNTRY_CODE! : 'TH',
  ticketmasterTimeoutMs: boundedNumber(process.env.TICKETMASTER_TIMEOUT_SECONDS, 10, 3, 30) * 1000,
  concertSchedulerEnabled: process.env.CONCERT_SCHEDULER_ENABLED !== 'false',
  concertDetailLimit: Math.floor(boundedNumber(process.env.CONCERT_DETAIL_LIMIT, 200, 20, 1000)),
  concertLocalResearch: process.env.CONCERT_LOCAL_RESEARCH_ENABLED === 'true',
  concertReuseAuthorized: (process.env.CONCERT_REUSE_AUTHORIZED_SOURCES || '').split(',').map(item => item.trim()).filter(Boolean),
  concertReportDirectory: process.env.CONCERT_REPORT_DIRECTORY || '',
  bandsintownAppId: process.env.BANDSINTOWN_APP_ID || '',
  metaToken: process.env.META_ACCESS_TOKEN || '',
  metaVersion: process.env.META_GRAPH_VERSION || 'v22.0',
  instagramGraphToken: process.env.INSTAGRAM_GRAPH_ACCESS_TOKEN || '',
  instagramGraphUserId: process.env.INSTAGRAM_GRAPH_IG_USER_ID || '',
  instagramGraphVersion: /^v\d+\.\d+$/.test(process.env.INSTAGRAM_GRAPH_API_VERSION || '') ? process.env.INSTAGRAM_GRAPH_API_VERSION! : 'v25.0',
  instagramGraphTokenExpiresAt: process.env.INSTAGRAM_GRAPH_TOKEN_EXPIRES_AT || '',
  socialSchedulerEnabled: process.env.SOCIAL_SCHEDULER_ENABLED !== 'false',
  socialSyncIntervalMinutes: boundedNumber(process.env.SOCIAL_SYNC_INTERVAL_MINUTES, 60, 15, 1440),
  socialStaleAfterMinutes: boundedNumber(process.env.SOCIAL_STALE_AFTER_MINUTES, 60, 15, 10080),
  instagramRequestSpacingSeconds: boundedNumber(process.env.INSTAGRAM_REQUEST_SPACING_SECONDS, 60, 30, 600),
  instagramMediaRefreshHours: boundedNumber(process.env.INSTAGRAM_MEDIA_REFRESH_HOURS, 6, 1, 48),
  instagramUsagePausePercent: boundedNumber(process.env.INSTAGRAM_USAGE_PAUSE_PERCENT, 75, 50, 90),
  instagramRateLimitCooldownMinutes: boundedNumber(process.env.INSTAGRAM_RATE_LIMIT_COOLDOWN_MINUTES, 60, 30, 360),
  googleRoutesEnabled: process.env.GOOGLE_ROUTES_ENABLED === 'true',
  googleRoutesKey: process.env.GOOGLE_ROUTES_API_KEY || '',
  googleRoutesTimeoutMs: boundedNumber(process.env.GOOGLE_ROUTES_TIMEOUT_SECONDS, 5, 2, 30) * 1000,
  agodaEnabled: process.env.AGODA_ENABLED === 'true',
  agodaClientId: process.env.AGODA_CLIENT_ID || '',
  agodaClientSecret: process.env.AGODA_CLIENT_SECRET || '',
  agodaTokenUrl: process.env.AGODA_TOKEN_URL || '',
  agodaSearchUrl: process.env.AGODA_SEARCH_URL || '',
  agodaEnvironment: process.env.AGODA_ENV === 'production' ? 'production' : 'sandbox',
  agodaPropertyIds: process.env.AGODA_PROPERTY_IDS_JSON || '{}',
  googleMapsKey: process.env.GOOGLE_MAPS_API_KEY || '',
  adminEmail: process.env.ADMIN_EMAIL || '',
  adminPassword: process.env.ADMIN_PASSWORD || '',
};
