import type { BiographySection } from './artist-biographies.js';
import type { CuratedArtistProfile } from './artist-profiles.js';

// Original Thai summaries. Historical release/roster claims retain their dates.
const gmm = (id: number) => 'https://www.gmmgrammy.com/newsroom/news-single.php?id=' + id;
const section = (heading: string, body: string, sourceUrl: string, sourceLabel: string): BiographySection => ({ heading, body, sourceUrl, sourceLabel });
type ExpandedProfile = CuratedArtistProfile & { name: string; kind: 'band' | 'solo' };
const interview = 'https://asianstyle.cz/filmy-tv/110196-daou-offroad-mluvi-o-sve-spolecne-ceste-o-tom-co-si-zamilovali-na-evrope-rolich-ktere-by-si-chteli-vyzkouset-a-novych-projektech/';
const consulate = 'https://newyork.thaiembassy.org/en/content/daou-offroad-from-chanel-one-31-paid-a-courtesy-c';

export const expandedArtistProfiles: ExpandedProfile[] = [
  { slug: 'potato', name: 'POTATO', kind: 'band', genres: ['rock'], bio: 'วงร็อกไทยที่ออกอัลบั้มชุดที่ 9 DOT ในปี 2569 และมีผลงานต่อเนื่องทั้งเพลงและการแสดงสด', sourceUrl: gmm(10456), sourceLabel: 'GMM Music — 16 กันยายน 2569', biography: [
    section('เส้นทางผ่านอัลบั้ม DOT', 'POTATO เป็นวงร็อกไทยที่มีผลงานอัลบั้มต่อเนื่อง โดยข่าวของ GMM Music ลงวันที่ 16 กันยายน 2569 ระบุว่า DOT เป็นอัลบั้มลำดับที่เก้าของวง และนำเสนอหลายด้านของความรู้สึกและประสบการณ์ผ่านเพลงในชุดนี้', gmm(10456), 'GMM Music — 16 กันยายน 2569'),
    section('เพลงในช่วงปี 2569', 'อัลบั้ม DOT รวมเพลง จำฉันวันนี้ ยินดี ชีวิตวุ่นวาย พนักงานใหม่บนโลกใบนี้ เพลิดเพลิน และ อย่าทำเป็นเหมือนว่าเข้าใจ ชื่อผลงานเหล่านี้ช่วยติดตามพัฒนาการของวงในช่วงการออกอัลบั้มดังกล่าว', gmm(10456), 'GMM Music — รายละเอียดอัลบั้ม DOT'),
    section('กิจกรรมร่วมกับแฟนเพลง', 'ประกาศเดียวกันแจ้งกิจกรรม POTATO FAN MEET จุดนัดพบ ที่ Cloud 11 Hall วันที่ 10 ตุลาคม 2569 สองรอบเวลา 14:00 และ 19:00 น. เป็นกิจกรรมเข้าชมฟรีโดยมีขั้นตอนลงทะเบียน จึงควรตรวจเงื่อนไขกับผู้จัดก่อนเข้าร่วม', gmm(10456), 'GMM Music — ประกาศแฟนมีต'),
  ] },
  { slug: 'klear', name: 'KLEAR', kind: 'band', genres: ['pop', 'rock'], bio: 'วงร็อกไทยเจ้าของอัลบั้ม Grow In The Dark และคอนเสิร์ต THE KLEAR SKY; รายชื่อสมาชิกอ้างตามประกาศปี 2565', sourceUrl: gmm(9604), sourceLabel: 'GMM SHOW — ประกาศปี 2565', biography: [
    section('วงและสมาชิกตามประกาศ', 'ประกาศ THE KLEAR SKY CONCERT ในปี 2565 ระบุสมาชิก KLEAR ได้แก่ แพท รัณนภันต์ ยั่งยืนพูนชัย ร้องนำ ณัฐ ณัฐวัฒน์ แสงวิจิตร กีตาร์ คี คียาภัทร โพธิ์วงศ์ไพรเลิศ เบส และนัฐ นิลวิเชียร กลอง ข้อมูลนี้เป็นรายชื่อในช่วงประกาศคอนเสิร์ต', gmm(9604), 'GMM SHOW — รายชื่อสมาชิกปี 2565'),
    section('ผลงานอัลบั้ม', 'GMM Grammy กล่าวถึงอัลบั้ม GROW IN THE DARK ของ KLEAR ในข่าวความร่วมมือกับ VGI วันที่ 30 มิถุนายน 2563 โดยระบุเป็นอัลบั้มเต็มสิบเพลง การอ้างอิงนี้ยืนยันผลงานในช่วงเวลานั้นและไม่ใช้แทนวันเปิดตัวอัลบั้มที่ไม่มีหลักฐานเพิ่มเติม', gmm(7653), 'GMM Grammy — 30 มิถุนายน 2563'),
    section('THE KLEAR SKY CONCERT', 'THE KLEAR SKY CONCERT เป็นคอนเสิร์ตใหญ่ครั้งที่สองตามประกาศของ GMM SHOW จัดวันที่ 15 ตุลาคม 2565 ที่ธันเดอร์โดม เมืองทองธานี หลังแผนงานต้องเลื่อนเนื่องจากโควิด วงอธิบายแนวคิดของงานผ่านภาพท้องฟ้าและเพลงที่อยู่กับความรู้สึกของผู้ฟัง', gmm(9604), 'GMM SHOW — คอนเสิร์ตปี 2565'),
  ] },
  { slug: 'lomosonic', name: 'LOMOSONIC', kind: 'band', genres: ['alternative', 'rock'], bio: 'วงร็อกจาก genie records; ข่าวเดือนกันยายน 2569 ระบุสมาชิก บอย ป้อม ปิติ และออตโต้', sourceUrl: gmm(10462), sourceLabel: 'GMM Music — 28 กันยายน 2569', biography: [
    section('วงและสมาชิก', 'ข่าว GMM Music วันที่ 28 กันยายน 2569 ระบุ LOMOSONIC เป็นวงร็อกภายใต้ genie records มีอริย์ธัช พลตาล หรือบอย ร้องนำ ฉัตรชัย งามสิริมงคลชัย หรือป้อม กีตาร์ ปิติ สหพงศ์ กีตาร์ และชาญเดช จันทร์จำเริญ หรือออตโต้ กลอง', gmm(10462), 'GMM Music — รายชื่อสมาชิกเดือนกันยายน 2569'),
    section('อัลบั้มแรกและการย้อนกลับไปหาผลงาน', 'อัลบั้ม ดอกไม้ไฟ หรือ Fireworks เป็นอัลบั้มแรกของวง ข่าวปี 2569 กล่าวถึงผลงานนี้เมื่อผ่านไปสิบเจ็ดปี และวงนำเพลงในอัลบั้มทั้งสิบเพลงกลับมาเล่นเรียงตามแทร็กในการแสดง Lost Frequencies II', gmm(10462), 'GMM Music — อัลบั้มดอกไม้ไฟ'),
    section('Lost Frequencies II', 'LOMOSONIC Lost Frequencies II เป็นส่วนหนึ่งของ FUNJAI SOLO SERIES 03 จัดวันที่ 25 กันยายน 2569 ที่ The Street Hall Ratchada นอกจากเพลงในอัลบั้มแรก ยังมีเพลง ขอ และรักครั้งสุดท้ายในช่วงท้าย รายงานนี้บันทึกการแสดงที่เกิดขึ้นแล้ว', gmm(10462), 'GMM Music — รายงานการแสดงสด'),
  ] },
  { slug: 'num-kala', name: 'NUM KALA', kind: 'solo', genres: ['rock'], bio: 'หนุ่ม กะลา หรือ ณพสิน แสงสุวรรณ ศิลปินร็อกที่จัด FIRST IMPACT CONCERT ในปี 2565', sourceUrl: gmm(9674), sourceLabel: 'GMM SHOW — 19 กันยายน 2565', biography: [
    section('ตัวตนและเส้นทางงานเพลง', 'หนุ่ม กะลา ใช้ชื่อ NUM KALA ในการทำงานเพลง และมีชื่อจริงว่า ณพสิน แสงสุวรรณ ตามรายงานของ GMM SHOW ในปี 2565 รายงานกล่าวถึงการทำงานในช่วง genie records และเพลงที่ผู้ฟังคุ้นเคยจากเส้นทางของกะลา', gmm(9674), 'GMM SHOW — ประวัติในช่วงปี 2565'),
    section('MY NAME IS NUM KALA', 'MY NAME IS NUM KALA FIRST IMPACT CONCERT เป็นคอนเสิร์ตเดี่ยวที่อิมแพ็ค อารีน่าในปี 2565 ภายใต้การสร้างสรรค์ของ GFEST ใน GMM SHOW งานนำเพลงต่างช่วงของศิลปินมาจัดเป็นการแสดง พร้อมแขกรับเชิญและการออกแบบโปรดักชั่น', gmm(9674), 'GMM SHOW — FIRST IMPACT CONCERT'),
    section('เพลงและการแสดงร่วม', 'รายงานคอนเสิร์ตกล่าวถึงเพลง ทุกวันได้ไหม ปล่อย และจม รวมถึงช่วงย้อนเพลง MY NAME IS KALA และแม่ครับจากปี 2542 มีศิลปินรับเชิญร่วมแสดง เช่น บอย Peacemaker และแอ๊ด คาราบาว จึงสะท้อนผลงานข้ามช่วงเวลาในการแสดงเดียว', gmm(9674), 'GMM SHOW — เพลงและแขกรับเชิญ'),
  ] },
  { slug: 'd-gerrard', name: 'D GERRARD', kind: 'solo', genres: ['pop', 'hip-hop'], bio: 'ศิลปินนักร้องและนักแต่งเพลง เจ้าของ Galaxy และรถไฟบนฟ้า; มีทั้งผลงานเพลงและการแสดงใน 4 Kings', sourceUrl: 'https://mixmagazine.in.th/00010878', sourceLabel: 'ข่าวประชาสัมพันธ์ Warner Music Thailand — 13 พฤศจิกายน 2566', biography: [
    section('การเริ่มเป็นที่รู้จักและอัลบั้ม', 'ข่าวประชาสัมพันธ์ Warner Music Thailand ปี 2566 ระบุว่า D GERRARD เป็นที่รู้จักจาก Galaxy ในปี 2562 ตามด้วย Scientist Luxury Friend Zone และ Paradise Online มีอีพี ZERO และอัลบั้มเต็มชุดแรกใช้ชื่อ D GERRARD', 'https://mixmagazine.in.th/00010878', 'Warner Music Thailand — ข่าวประชาสัมพันธ์บน MiX'),
    section('งานเพลงและการแสดง', 'D GERRARD ทำงานทั้งการร้อง แต่งเพลง และผลิตเพลง ขณะเดียวกันมีผลงานแสดงในภาพยนตร์ 4 Kings ทั้งสองภาค ตามข่าวประชาสัมพันธ์เดือนธันวาคม 2567 ส่วนเพลง Bestfriend ในปี 2566 เป็นการร่วมงานกับศิลปินจากหลายชาติอาเซียน', 'https://www.mixmagazine.in.th/00014018', 'Warner Music Thailand — 6 ธันวาคม 2567'),
    section('Galaxy Express และ ATLANTIS', 'รถไฟบนฟ้า หรือ Galaxy Express เป็นผลงานที่ปล่อยในช่วงต้นปี 2567 ส่วน ATLANTIS ตามมาในช่วงปลายปี โดยศิลปินเล่าว่านำความสนใจเรื่องเมืองในตำนานมาใช้สร้างเรื่องราวและออกแบบเสียงดนตรีของเพลง', 'https://www.mixmagazine.in.th/00014018', 'Warner Music Thailand — ที่มาของ ATLANTIS'),
  ] },
  { slug: 'f-hero', name: 'F.HERO', kind: 'solo', genres: ['hip-hop'], bio: 'แร็ปเปอร์ไทยที่มีผลงานร่วมกับ MILLI, Changbin, Bodyslam, BABYMETAL และ BALLISTIK BOYZ', sourceUrl: 'https://www.ldh.co.jp/chh/news/detail.php?lang=eng&newsid=0000046651&site=TRIBE', sourceLabel: 'LDH — 28 มีนาคม 2567', biography: [
    section('แร็ปเปอร์และการร่วมงานข้ามประเทศ', 'F.HERO เป็นแร็ปเปอร์ไทยที่มีงานร่วมกับศิลปินหลากหลายกลุ่ม LDH ระบุการร่วมงานของเขาใน Meant to be กับ BALLISTIK BOYZ และ BOOM BOOM CASH ซึ่งออกผ่าน HIGH CLOUD วันที่ 28 มีนาคม 2567', 'https://www.ldh.co.jp/chh/news/detail.php?lang=eng&newsid=0000046651&site=TRIBE', 'LDH — รายงานการร่วมงาน'),
    section('Mirror Mirror', 'Mirror Mirror เป็นผลงานร่วมของ F.HERO กับ MILLI และ Changbin ตามเครดิตการเผยแพร่บน Spotify ในปี 2564 โดยมี HIGH CLOUD เป็นผู้เผยแพร่ ข้อมูลเครดิตยืนยันการร่วมงานในเพลงนี้โดยไม่ใช้ตัดสินสังกัดถาวรของผู้ร่วมงานแต่ละคน', 'https://open.spotify.com/album/3R5wfZr723i5qfyPCAuUnS', 'Spotify — เครดิต Mirror Mirror'),
    section('LEAVE IT ALL BEHIND', 'F.HERO ร่วมกับ Bodyslam และ BABYMETAL ใน LEAVE IT ALL BEHIND ที่เผยแพร่เดือนมีนาคม 2567 เป็นอีกผลงานที่นำศิลปินไทยและญี่ปุ่นมาร่วมกัน แหล่งเผยแพร่เพลงระบุศิลปินร่วมและช่วงเวลาของงานให้ตรวจกลับได้', 'https://open.spotify.com/intl-fr/album/0nBFE2T0w9ioMdSjGMOYAR', 'Spotify — เครดิต LEAVE IT ALL BEHIND'),
  ] },
  { slug: 'urboytj', name: 'URBOYTJ', kind: 'solo', genres: ['pop', 'hip-hop'], bio: 'แร็ปเปอร์และโปรดิวเซอร์ไทย เจ้าของ Selfmade และ URMAN ซึ่งผสมงานป็อปกับแร็ป', sourceUrl: 'https://music.apple.com/us/album/urman/1713311551', sourceLabel: 'Apple Music — URMAN', accounts: [{ platform: 'website', url: 'https://linktr.ee/urboytj', evidenceUrl: 'https://linktr.ee/urboytj' }], biography: [
    section('ผลงานเดี่ยวและบทบาทโปรดิวเซอร์', 'URBOYTJ มีผลงานเดี่ยว เช่น เค้าก่อน และวายร้าย ในปี 2559 ตามรายการเผยแพร่ของ Apple Music บทนำอัลบั้ม URMAN อธิบายเขาในบทบาทแร็ปเปอร์และโปรดิวเซอร์ที่ใช้ประสบการณ์ของตนถ่ายทอดผ่านเพลงป็อปแร็ป', 'https://music.apple.com/us/album/urman/1713311551', 'Apple Music — ผลงาน URBOYTJ'),
    section('จาก Selfmade ถึง URMAN', 'Selfmade เผยแพร่ปี 2563 ก่อน URMAN ซึ่งออกวันที่ 9 พฤศจิกายน 2566 มีเก้าเพลงและความยาวรวมประมาณยี่สิบแปดนาที อัลบั้มหลังสำรวจเรื่องความรักและความโดดเดี่ยวในหลายรูปแบบดนตรีตามคำอธิบายของบริการเผยแพร่', 'https://music.apple.com/us/album/urman/1713311551', 'Apple Music — รายละเอียดอัลบั้ม'),
    section('การร่วมสร้างงานเพลง', 'URMAN มีแขกร่วมงาน ได้แก่ HYE จาก Paper Planes สิงโต นำโชค และ OG BOBBY ตามบทนำของ Apple Music ความร่วมมือเหล่านี้เป็นเครดิตของอัลบั้ม ไม่ใช่หลักฐานการเข้าร่วมวงหรือย้ายสังกัดของศิลปินรับเชิญ', 'https://music.apple.com/us/album/urman/1713311551', 'Apple Music — ศิลปินร่วมอัลบั้ม'),
  ] },
  { slug: 'joey-boy', name: 'Joey Boy', kind: 'solo', genres: ['hip-hop'], bio: 'ศิลปินฮิปฮอปไทยที่มีผลงานตั้งแต่ First Album และ Joey Man จนถึง Fun Again และอัลบั้ม JOEY BOY 30+', sourceUrl: 'https://open.spotify.com/artist/4e7aoOMNnIJCw4CEOlDVjU', sourceLabel: 'Spotify — ผลงาน Joey Boy', biography: [
    section('ผลงานช่วงแรก', 'รายการผลงานของ Joey Boy บน Spotify มี First Album ปี 2538 Joey Man ปี 2539 และ Bangkok ปี 2541 ข้อมูลการเผยแพร่เหล่านี้แสดงเส้นทางงานเพลงหลายช่วง โดยปีในบริการดิจิทัลอาจแตกต่างจากวันจำหน่ายฉบับแรก', 'https://open.spotify.com/artist/4e7aoOMNnIJCw4CEOlDVjU', 'Spotify — รายการอัลบั้ม'),
    section('ก้านคอคลับ', 'อัลบั้มรวม ก้านคอคลับ เผยแพร่ในปี 2545 มี Joey Boy ร่วมอยู่ในหลายเพลง เช่น Gancore Club Bangkok Bad Boy Rapper Lan-Na และ DJ เครดิตรายการนี้เป็นหลักฐานการร่วมสร้างงานฮิปฮอปกับศิลปินอื่นในโครงการ', 'https://open.spotify.com/album/3DmJSFBIQnLmeMhsEN4VlO', 'Spotify — ก้านคอคลับ'),
    section('งานเพลงในช่วงต่อมา', 'รายการผลงานรวม Fun Again ปี 2554 และ JOEY BOY 30+ อัลบั้มที่ 30 กว่า ปี 2557 รวมถึงซิงเกิล คนโสดในคอนเสิร์ต ปี 2566 จึงมีเพลงทั้งรูปแบบอัลบั้มและซิงเกิลให้ติดตาม โดยยังไม่ใช้รายการเพลงตัดสินสัญญาค่ายปัจจุบัน', 'https://open.spotify.com/artist/4e7aoOMNnIJCw4CEOlDVjU', 'Spotify — ผลงานต่างช่วงเวลา'),
  ] },
  ...(['daou-pittaya', 'offroad-kantapon'] as const).map(slug => ({
    slug, name: slug === 'daou-pittaya' ? 'Daou Pittaya' : 'Offroad Kantapon', kind: 'solo' as const, genres: ['t-pop'],
    bio: slug === 'daou-pittaya' ? 'ต้าห์อู๋ พิทยา แซ่ฉั่ว ศิลปินและนักแสดงที่มีเส้นทางจาก LAZ iCON และ LAZ1' : 'ออฟโรด กันตภณ จินดาทวีผล ศิลปินและนักแสดงที่มีเส้นทางจาก LAZ iCON และ LAZ1',
    sourceUrl: consulate, sourceLabel: 'สถานกงสุลใหญ่ ณ นครนิวยอร์ก — พฤษภาคม 2569', biography: [
      section('ตัวตนและจุดเริ่มต้น', `${slug === 'daou-pittaya' ? 'Daou Pittaya หรือพิทยา แซ่ฉั่ว' : 'Offroad Kantapon หรือกันตภณ จินดาทวีผล'} มีเส้นทางเริ่มจากรายการ LAZ iCON ในปี 2564 และการทำงานใน LAZ1 ตามบทสัมภาษณ์ร่วมปี 2569 ศิลปินทั้งสองเล่าถึงการฝึกและประสบการณ์ช่วงแข่งขันซึ่งเป็นจุดเริ่มต้นของการร่วมงาน`, interview, 'Asianstyle — บทสัมภาษณ์ศิลปินโดยตรง 2 มิถุนายน 2569'),
      section('การทำงานเพลงและการแสดง', 'บทสัมภาษณ์ปี 2569 กล่าวถึงเส้นทางหลัง LAZ1 และการทำงานร่วมกันใน Love in Translation, Century of Love และ The Wicked Game ข้อมูลนี้บันทึกประสบการณ์ที่ศิลปินเล่าเอง ส่วนการอยู่ร่วมวงในอดีตไม่ใช้แทนสถานะวงหรือค่ายปัจจุบัน', interview, 'Asianstyle — บทสัมภาษณ์ศิลปินโดยตรง'),
      section('กิจกรรมกับผู้ชมต่างประเทศ', 'สถานกงสุลใหญ่ ณ นครนิวยอร์กระบุการเยือนของ Daou และ Offroad พร้อมทีมช่อง ONE 31 วันที่ 14 พฤษภาคม 2569 ระหว่างเดินทางไปแฟนมีตครั้งแรกในสหรัฐฯ ที่ Melrose Ballroom วันที่ 16 พฤษภาคม ข้อมูลนี้ยืนยันกิจกรรมและทีมผู้ร่วมเดินทางในช่วงนั้น', consulate, 'สถานกงสุลใหญ่ ณ นครนิวยอร์ก — รายงานกิจกรรม'),
    ],
  })),
  { slug: 'lykn', name: 'LYKN', kind: 'band', genres: ['t-pop'], bio: 'บอยกรุ๊ปห้าคนจาก Project Alpha ภายใต้ RISER MUSIC มี William, Lego, Tui, Hong และ Nut', sourceUrl: 'https://www.universal-music.co.jp/lykn/biography/', sourceLabel: 'Universal Music Japan — ประวัติ LYKN', biography: [
    section('การก่อตั้งและสมาชิก', 'LYKN เป็นบอยกรุ๊ปห้าคนที่คัดเลือกจาก Project Alpha ในปี 2566 ตามประวัติบน Universal Music Japan มี William Lego Tui Hong และ Nut อยู่ภายใต้ RISER MUSIC ซึ่งเป็นค่ายเพลงของ GMMTV', 'https://www.universal-music.co.jp/lykn/biography/', 'Universal Music Japan — สมาชิกและค่าย'),
    section('ชื่อวงและการแสดง', 'ชื่อ LYKN มาจากคำ Lycanthrope ตามคำอธิบายของค่าย สื่อถึงพลังและการแสดงของสมาชิก วงนำเสนอทั้งการร้องและเต้น และได้แสดงในเทศกาลไทยที่โตเกียวเดือนพฤษภาคม 2566 ซึ่งเป็นการแสดงครั้งแรกของวงในญี่ปุ่น', 'https://www.universal-music.co.jp/lykn/biography/', 'Universal Music Japan — ที่มาของวง'),
    section('DUSK & DAWN และงานต่างประเทศ', 'ประวัติของค่ายกล่าวถึงการออกอัลบั้มแรก DUSK & DAWN และแผนเวิลด์ทัวร์ในปี 2569 ที่รวมโตเกียวและโอซาก้า รวมถึงงานที่ Zepp และ Toyosu PIT ในช่วงก่อนหน้า กำหนดการทัวร์เป็นข้อมูลประกาศและควรตรวจต้นทางอีกครั้งก่อนเดินทาง', 'https://www.universal-music.co.jp/lykn/biography/', 'Universal Music Japan — อัลบั้มและกิจกรรม'),
  ] },
  { slug: 'nene', name: 'Nené', kind: 'solo', genres: ['pop', 't-pop', 'mandopop'], bio: 'เนเน่ พรนับพัน พรเพ็ญพิพัฒน์ หรือ Zheng Naixin ศิลปินไทยที่มีผลงานทั้งภาษาไทยและจีน', sourceUrl: 'https://open.spotify.com/artist/6xSImf4WfS9VAr2jpd9BAo', sourceLabel: 'Spotify — ประวัติและผลงาน Nené', biography: [
    section('เส้นทางจากกลุ่มศิลปิน', 'ประวัติของ Nené บนหน้า Spotify กล่าวถึงการทำงานกับ MilkShake ในปี 2558 ก่อนการเข้าร่วมรายการ Produce Camp และกลุ่ม BonBon Girls 303 เธอใช้ชื่อ Zheng Naixin ในงานภาษาจีน และมีงานเพลงกับการแสดงควบคู่กัน', 'https://open.spotify.com/artist/6xSImf4WfS9VAr2jpd9BAo', 'Spotify — ประวัติศิลปิน'),
    section('การทำงานเดี่ยว', 'ประวัติในบริการเผยแพร่ระบุว่ากลุ่ม BonBon Girls 303 สิ้นสุดช่วงกิจกรรมในเดือนกรกฎาคม 2565 และเนเน่ประกาศร่วมงานกับ Sony Music ในเดือนเดียวกัน มีซิงเกิล Promise และอัลบั้มภาษาจีนในปี 2566 ข้อมูลสังกัดนี้อ้างตามเหตุการณ์ในปี 2565', 'https://open.spotify.com/artist/6xSImf4WfS9VAr2jpd9BAo', 'Spotify — เส้นทางงานเดี่ยว'),
    section('เพลงไทยและ Mad Love', 'รายการเผยแพร่ปี 2567 มีอัลบั้ม Mad Love และเพลง สาย หรือ Gone ใจว่าใช่ หรือ 100% YOU บังเอิญ หรือ Loving U รวมถึง Cosmic Love และ All to myself ผลงานเหล่านี้ยืนยันกิจกรรมเพลงหลายภาษา โดยไม่ใช้แทนการตรวจยอดผู้ฟังปัจจุบัน', 'https://open.spotify.com/artist/6xSImf4WfS9VAr2jpd9BAo', 'Spotify — รายการผลงานปี 2567'),
  ] },
  { slug: 'nunew', name: 'NuNew', kind: 'solo', genres: ['pop', 't-pop'], bio: 'นุนิว ชวรินทร์ เพริศพิริยะวงศ์ นักร้องและนักแสดงจาก DMD MUSIC เจ้าของเพลงหมอนอิงและงานเพลงประกอบซีรีส์', sourceUrl: 'https://universalmusic.fr/artistes/36904686278', sourceLabel: 'Universal Music — ประวัติ NuNew', accounts: [{ platform: 'instagram', url: 'https://www.instagram.com/new_cwr/', evidenceUrl: 'https://www.youtube.com/watch?v=nU5xA_skKzk' }], biography: [
    section('การเริ่มทำงานบันเทิง', 'NuNew หรือชวรินทร์ เพริศพิริยะวงศ์ เข้าร่วม DMD Reality ในปี 2564 และมีบทบาทในซีรีส์ Cutie Pie ปี 2565 ตามประวัติของ Universal Music ส่วนช่อง DMD MUSIC แนะนำตัวเขาเป็นศิลปินในวิดีโอเดือนมิถุนายน 2566', 'https://universalmusic.fr/artistes/36904686278', 'Universal Music — ประวัติการทำงาน'),
    section('จากเพลงประกอบสู่ซิงเกิลเดี่ยว', 'นุนิวมีผลงานเพลงประกอบ Cutie Pie และเพลง รักแท้ สำหรับซีรีส์ To Sir, With Love ก่อนเปิดตัวงานเดี่ยว Anything หรือหมอนอิง ในเดือนกรกฎาคม 2566 แล้วตามด้วยเพลง เอ๊ะ! ซึ่งร่วมงานกับแทน Lipta', 'https://universalmusic.fr/artistes/36904686278', 'Universal Music — เส้นทางเพลงเดี่ยว'),
    section('งานร่วมและการแสดงสด', 'ประวัติของ Universal Music บันทึกคอนเสิร์ตร่วมกับ Zee Pruk วันที่ 30 กันยายนและ 1 ตุลาคม 2566 และเพลงร่วมในปี 2567 เช่น รักเธอเต็มฟีด กับ DMD Boys ปิ๊งไปป่ะกับ Zee Pruk และ Blooming Just For You กับ Paul Kim', 'https://universalmusic.fr/artistes/36904686278', 'Universal Music — ผลงานร่วมและคอนเสิร์ต'),
  ] },
];
