'use client';
import { useState } from 'react';
import { Search } from 'lucide-react';
import { useData } from '../../components/use-data';
import { ConcertCard } from '../../components/cards';
import type { Concert, Page } from '../../lib/api';

export default function ConcertsPage() {
  const [q, setQ] = useState(''); const [city, setCity] = useState(''); const [country, setCountry] = useState(''); const [status, setStatus] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [page, setPage] = useState(1);
  const result = useData<Page<Concert>>('/concerts?' + new URLSearchParams({ q, city, country, status, minPrice, maxPrice, page: String(page) }));
  return <div className="container page"><div className="page-heading"><span className="eyebrow">LIVE MUSIC AHEAD</span><h1>ไปเจอกันหน้าเวที<span className="accent-dot">.</span></h1><p>รวมงานจากแหล่งที่ระบบเข้าถึงได้ พร้อมสถานะ ราคา และลิงก์ต้นทาง</p></div><div className="toolbar"><label className="search-field"><Search size={19}/><input placeholder="ชื่อคอนเสิร์ต หรือสถานที่" value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }}/></label><input className="small-input" placeholder="เมือง" value={city} onChange={(e) => { setCity(e.target.value); setPage(1); }}/><select value={country} onChange={(e) => { setCountry(e.target.value); setPage(1); }} aria-label="ประเทศ"><option value="">ทุกประเทศ</option><option value="TH">ไทย</option><option value="SG">สิงคโปร์</option><option value="JP">ญี่ปุ่น</option><option value="KR">เกาหลีใต้</option></select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} aria-label="สถานะ"><option value="">กำลังจะมา</option><option value="postponed">เลื่อน</option><option value="cancelled">ยกเลิก</option></select><input className="small-input" type="number" min="0" placeholder="ราคาต่ำสุด" value={minPrice} onChange={(e) => { setMinPrice(e.target.value); setPage(1); }}/><input className="small-input" type="number" min="0" placeholder="งบสูงสุด" value={maxPrice} onChange={(e) => { setMaxPrice(e.target.value); setPage(1); }}/></div>{result.error && <p className="notice error">{result.error}</p>}{result.loading && <p className="loading">กำลังโหลดคอนเสิร์ต...</p>}<div className="concert-grid">{result.data?.items.map((concert) => <ConcertCard key={concert.id} concert={concert}/>)}</div>{result.data?.items.length === 0 && <p className="empty">ยังไม่พบงานตามตัวกรองนี้ แหล่งข้อมูลบางแห่งอาจยังไม่เชื่อมต่อ</p>}<div className="pager"><button disabled={page === 1} onClick={() => setPage(page - 1)}>ก่อนหน้า</button><span>หน้า {page} จาก {Math.max(1, Math.ceil((result.data?.total || 0) / 20))}</span><button disabled={page * 20 >= (result.data?.total || 0)} onClick={() => setPage(page + 1)}>ถัดไป</button></div></div>;
}
