'use client';
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Suspense } from 'react';
import { Send, Sparkles } from 'lucide-react';
import { api, price, type Concert, type Page } from '../../lib/api';
import { useData } from '../../components/use-data';

type Estimate = { concert: { title: string; destination: string }; items: { kind: string; label: string; amount: number | null; priceType: 'estimate' | 'observed' | 'live' | 'unavailable'; note: string }[]; disclaimer: string };
function AssistantContent() {
  const params = useSearchParams(); const concerts = useData<Page<Concert>>('/concerts');
  const [message, setMessage] = useState(''); const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [concertId, setConcertId] = useState(params.get('concertId') || ''); const [origin, setOrigin] = useState('กรุงเทพมหานคร'); const [people, setPeople] = useState(1); const [nights, setNights] = useState(1); const [distanceKm, setDistanceKm] = useState(''); const [estimate, setEstimate] = useState<Estimate | null>(null);
  async function send(event: React.FormEvent) { event.preventDefault(); if (!message.trim()) return; setBusy(true); setError(''); try { const data = await api<{ answer: string }>('/chat', { method: 'POST', body: JSON.stringify({ message }) }); setAnswer(data.answer); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  async function calculate(event: React.FormEvent) { event.preventDefault(); setError(''); try { const data = await api<Estimate>('/trip-estimates', { method: 'POST', body: JSON.stringify({ concertId, origin, people, nights, distanceKm: Number(distanceKm) }) }); setEstimate(data); } catch (err) { setError((err as Error).message); } }
  return <div className="container page"><div className="page-heading"><span className="eyebrow">YOUR FAN COMPANION</span><h1>ผู้ช่วยของ<br/><em>แฟนเพลง</em></h1><p>ถามจากข้อมูลศิลปิน ข่าว และคอนเสิร์ตที่ระบบมี พร้อมแยกงบที่ทราบราคาและงบประมาณ</p></div><div className="assistant-grid"><section className="assistant-panel"><div className="panel-heading"><Sparkles size={21}/><h2>ถาม Encore AI</h2></div><div className="chat-area">{answer ? <p className="chat-answer">{answer}</p> : <p className="chat-placeholder">ลองถามว่า “ศิลปินที่ติดตามมีงานที่ไหนบ้าง?” หรือ “มีคอนเสิร์ตในกรุงเทพเดือนนี้ไหม?”</p>}</div><form onSubmit={send} className="chat-form"><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="พิมพ์คำถามของคุณ..."/><button disabled={busy} aria-label="ส่งคำถาม"><Send size={18}/></button></form><small>ต้องเข้าสู่ระบบ · หากเครื่อง AI ไม่พร้อม ข้อมูลศิลปินและคอนเสิร์ตยังใช้งานได้</small></section><section className="assistant-panel"><div className="panel-heading"><h2>วางแผนงบทริป</h2></div><form className="budget-form" onSubmit={calculate}><label>คอนเสิร์ต<select value={concertId} onChange={(e) => setConcertId(e.target.value)} required><option value="">เลือกคอนเสิร์ต</option>{concerts.data?.items.map((concert) => <option key={concert.id} value={concert.id}>{concert.title}</option>)}</select></label><label>เมืองต้นทาง<input value={origin} onChange={(e) => setOrigin(e.target.value)} required/></label><label>ระยะทางเที่ยวเดียว (กม.) สำหรับงบรถ/รถไฟ<input type="number" min="0" max="3000" value={distanceKm} onChange={(e) => setDistanceKm(e.target.value)} placeholder="ถ้าทราบ"/></label><div className="form-row"><label>จำนวนคน<input type="number" min="1" max="10" value={people} onChange={(e) => setPeople(Number(e.target.value))}/></label><label>จำนวนคืน<input type="number" min="0" max="14" value={nights} onChange={(e) => setNights(Number(e.target.value))}/></label></div><button className="button primary" type="submit">คำนวณงบ</button></form>{estimate && <div className="budget-results"><h3>{estimate.concert.title}</h3>{estimate.items.map((item) => <div key={item.kind} className="budget-line"><span>{item.label}<small>{item.priceType === 'live' ? 'ราคาสด' : item.priceType === 'observed' ? 'ราคาที่พบ' : item.priceType === 'estimate' ? 'ราคาประมาณ' : 'ไม่มีราคา'} · {item.note}</small></span><strong>{item.amount === null ? '—' : price(item.amount)}</strong></div>)}<p className="fine-print">{estimate.disclaimer}</p></div>}</section></div>{error && <p className="notice error">{error}</p>}</div>;
}
export default function AssistantPage() { return <Suspense fallback={<p className="loading">กำลังโหลด...</p>}><AssistantContent/></Suspense>; }
