'use client';
import { use, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, CalendarDays, MapPin, Ticket, Clock3 } from 'lucide-react';
import { api, date, price, stale, type Concert } from '../../../lib/api';
import { useData } from '../../../components/use-data';
import { ConcertReviews } from '../../../components/concert-reviews';
import { ConcertPoster } from '../../../components/concert-poster';
import { ConcertLocation } from '../../../components/concert-location';

export default function ConcertDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params); const result = useData<Concert>('/concerts/' + encodeURIComponent(slug)); const [message, setMessage] = useState(''); const concert = result.data;
  async function attended() { if (!concert) return; try { await api('/me/attendance/' + concert.id, { method: 'PUT' }); setMessage('บันทึกงานที่เคยไปแล้ว'); window.dispatchEvent(new CustomEvent('encore-attendance-change',{ detail: concert.id })); } catch (error) { setMessage((error as Error).message); } }
  return <div className="container page"><Link href="/concerts" className="back-link"><ArrowLeft size={17}/> กลับไปคอนเสิร์ตทั้งหมด</Link>{result.error && <p className="notice error">{result.error}</p>}{concert && <><section className="concert-detail"><div className="concert-detail-main"><ConcertPoster key={concert.id} concert={concert}/><span className="eyebrow">LIVE EVENT · {concert.country_code}</span><h1>{concert.title}</h1><div className="event-facts"><span><CalendarDays size={19}/>{date(concert.starts_at, concert.time_tba)}</span><span><MapPin size={19}/>{[concert.venue, concert.city].filter(Boolean).join(', ') || 'ยังไม่ระบุสถานที่'}</span><span><Ticket size={19}/>{concert.price_min != null ? price(concert.price_min,concert.currency) + (concert.price_max != null ? ' – ' + price(concert.price_max,concert.currency) : '') : 'ยังไม่ประกาศราคา'}</span></div>{concert.price_note && <p className="notice">{concert.price_note}</p>}<p className="event-description">{concert.description || 'ดูรายละเอียดเพิ่มเติมจากผู้จัดหรือผู้ขายบัตรผ่านลิงก์ต้นทาง'}</p><div className="tag-row"><span className="tag">สถานะ: {concert.status}</span>{stale(concert.last_verified_at) && <span className="tag warning">ข้อมูลอาจล้าสมัย</span>}</div>{concert.starts_at && new Date(concert.starts_at).getTime() + (concert.time_tba ? 86400000 : 0) < Date.now() && <button className="button secondary" onClick={attended}>บันทึกว่าเคยไปงานนี้</button>}{message && <p className="inline-message">{message}</p>}</div><aside className="source-panel"><h3><Clock3 size={19}/> แหล่งข้อมูล</h3><p>ตรวจล่าสุด: {date(concert.last_verified_at)}</p>{concert.sources?.map((source) => <a key={source.source_url || source.url} href={source.source_url || source.url} target="_blank" rel="noopener noreferrer">{source.source_name || source.source} <ArrowUpRight size={16}/></a>)}{!concert.sources?.length && <p>ยังไม่มีแหล่งอ้างอิงจากตัวดึง</p>}</aside></section><ConcertLocation key={concert.id} concert={concert}/><section className="section"><h2>รอบแสดง</h2><div className="link-list">{concert.performances?.map((performance) => <span className="tag" key={performance.id}>{performance.performance_label && <strong>{performance.performance_label} · </strong>}{date(performance.starts_at, performance.time_tba)} · {performance.status}{performance.is_current === false ? ' · รอบเดิม ไม่อยู่ในประกาศล่าสุด' : ''}</span>)}</div>{!concert.performances?.length && <p className="empty">ยังไม่ประกาศรอบแสดง</p>}</section><section className="section"><h2>ศิลปินในงาน</h2><div className="link-list">{concert.artists?.map((artist) => <Link key={artist.id} href={'/artists/' + artist.slug}>{artist.name} <ArrowUpRight size={17}/></Link>)}</div>{!concert.artists?.length && <p className="empty">ยังไม่จับคู่ศิลปินกับรายการนี้</p>}</section><Link className="button primary" href={'/assistant?concertId=' + concert.id}>วางแผนงบทริป</Link><ConcertReviews key={concert.id} concertId={concert.id}/></>}</div>;
}
