'use client';
import { useState } from 'react';
import Link from 'next/link';
import { api, type Artist, type Concert } from '../../lib/api';
import { useData, useSessionReset } from '../../components/use-data';

type Me = { user: { display_name: string; email: string; role: string }; follows: Artist[]; attendance: Concert[] };
export default function AccountPage() {
  const me = useData<Me>('/me'); const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [displayName, setDisplayName] = useState(''); const [error, setError] = useState('');
  useSessionReset(() => { setPassword(''); setEmail(''); setDisplayName(''); setError(''); });
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); try { await api('/auth/' + mode, { method: 'POST', body: JSON.stringify({ email, password, displayName }) }); await me.reload(); } catch (err) { setError((err as Error).message); } }
  async function logout() { try { await api('/auth/logout', { method: 'POST' }); } catch (err) { setError((err as Error).message); } }
  if (me.loading) return <div className="container page"><p className="loading" role="status">กำลังตรวจบัญชี...</p></div>;
  return <div className="container page"><div className="page-heading"><span className="eyebrow">YOUR SPACE</span><h1>บัญชีของฉัน</h1><p>เก็บศิลปินที่ติดตามและความทรงจำจากงานที่เคยไป</p></div>{me.data ? <div className="account-layout"><section className="panel"><h2>สวัสดี {me.data.user.display_name}</h2><p>{me.data.user.email}</p><button className="text-link" onClick={logout}>ออกจากระบบ</button>{me.data.user.role === 'admin' && <p><Link href="/admin">ไปหน้าผู้ดูแล →</Link> · <Link href="/admin/edit">แก้ไขข้อมูล →</Link></p>}</section><section className="panel"><h2>ศิลปินที่ติดตาม</h2>{me.data.follows.map((artist) => <p key={artist.id}><Link href={'/artists/' + artist.slug}>{artist.name} →</Link></p>)}{!me.data.follows.length && <p className="muted">ยังไม่ได้ติดตามศิลปิน <Link href="/artists">ค้นหาศิลปิน</Link></p>}<h2 className="spaced">งานที่เคยไป</h2>{me.data.attendance.map((concert) => <p key={concert.id}><Link href={'/concerts/' + concert.slug}>{concert.title} →</Link></p>)}{!me.data.attendance.length && <p className="muted">ยังไม่ได้บันทึกงาน</p>}</section></div> : <div className="auth-box"><div className="auth-switch"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>เข้าสู่ระบบ</button><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>สมัครสมาชิก</button></div><form onSubmit={submit}>{mode === 'register' && <label>ชื่อที่แสดง<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} minLength={2} required/></label>}<label>อีเมล<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/></label><label>รหัสผ่าน<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={mode === 'register' ? 10 : undefined} required/></label><button className="button primary" type="submit">{mode === 'login' ? 'เข้าสู่ระบบ' : 'สร้างบัญชี'}</button></form>{error && <p className="notice error">{error}</p>}</div>}</div>;
}
